-- Ledger settings and activity log texts
-- (fresh databases get these from the 0016 seed).
insert into public.translation_keys (key, namespace, is_user_editable) values
  ('lm.ledgerSettings', 'lm', false),
  ('ls.title', 'ls', false),
  ('ls.subtitle', 'ls', false),
  ('ls.infoTitle', 'ls', false),
  ('ls.infoSub', 'ls', false),
  ('ls.infoEditSub', 'ls', false),
  ('ls.owner', 'ls', false),
  ('ls.created', 'ls', false),
  ('ls.rulesTitle', 'ls', false),
  ('ls.related', 'ls', false),
  ('ls.linkMembers', 'ls', false),
  ('ls.linkActivity', 'ls', false),
  ('ls.linkTexts', 'ls', false),
  ('ls.transferHint', 'ls', false),
  ('ls.leaveSub', 'ls', false),
  ('al.title', 'al', false),
  ('al.subtitle', 'al', false),
  ('al.search', 'al', false),
  ('al.period', 'al', false),
  ('al.lastDays', 'al', false),
  ('al.allTime', 'al', false),
  ('al.allTypes', 'al', false),
  ('al.e_transaction', 'al', false),
  ('al.e_category', 'al', false),
  ('al.e_account', 'al', false),
  ('al.e_budget', 'al', false),
  ('al.e_category_rule', 'al', false),
  ('al.e_recurring', 'al', false),
  ('al.e_member', 'al', false),
  ('al.e_ledger', 'al', false),
  ('al.a_create', 'al', false),
  ('al.a_update', 'al', false),
  ('al.a_delete', 'al', false),
  ('al.k_create', 'al', false),
  ('al.k_update', 'al', false),
  ('al.k_delete', 'al', false),
  ('al.k_restore', 'al', false),
  ('al.clear', 'al', false),
  ('al.empty', 'al', false),
  ('al.emptyFiltered', 'al', false),
  ('al.today', 'al', false),
  ('al.yesterday', 'al', false),
  ('al.nEntries', 'al', false),
  ('al.details', 'al', false),
  ('al.hide', 'al', false),
  ('al.loadMore', 'al', false),
  ('al.privacyNote', 'al', false),
  ('al.hiddenValue', 'al', false),
  ('al.aRule', 'al', false),
  ('al.yes', 'al', false),
  ('al.no', 'al', false),
  ('al.f_amount', 'al', false),
  ('al.f_transaction_date', 'al', false),
  ('al.f_transaction_time', 'al', false),
  ('al.f_merchant_name', 'al', false),
  ('al.f_description', 'al', false),
  ('al.f_notes', 'al', false),
  ('al.f_category_id', 'al', false),
  ('al.f_account_id', 'al', false),
  ('al.f_transfer_account_id', 'al', false),
  ('al.f_transaction_type', 'al', false),
  ('al.f_status', 'al', false),
  ('al.f_paid_by_user_id', 'al', false),
  ('al.f_categorized_by', 'al', false),
  ('al.f_category_rule_id', 'al', false),
  ('al.f_needs_review', 'al', false),
  ('al.f_exclude_from_reports', 'al', false),
  ('al.f_is_reconciled', 'al', false),
  ('al.f_currency_code', 'al', false),
  ('al.f_name', 'al', false),
  ('al.f_parent_id', 'al', false),
  ('al.f_category_type', 'al', false),
  ('al.f_is_shared', 'al', false),
  ('al.f_is_archived', 'al', false),
  ('al.f_color', 'al', false),
  ('al.f_owner_id', 'al', false),
  ('al.f_account_type_code', 'al', false),
  ('al.f_opening_balance', 'al', false),
  ('al.f_opening_date', 'al', false),
  ('al.f_credit_limit', 'al', false),
  ('al.f_institution_name', 'al', false),
  ('al.f_account_number_last4', 'al', false),
  ('al.f_include_in_net_worth', 'al', false),
  ('al.f_rollover', 'al', false),
  ('al.f_warning_threshold_pct', 'al', false),
  ('al.f_period_type', 'al', false),
  ('al.f_pattern', 'al', false),
  ('al.f_is_active', 'al', false),
  ('al.f_apply_on_import', 'al', false),
  ('al.f_priority', 'al', false),
  ('al.f_frequency', 'al', false),
  ('al.f_interval_count', 'al', false),
  ('al.f_start_date', 'al', false),
  ('al.f_end_date', 'al', false),
  ('al.f_day_of_month', 'al', false),
  ('al.f_auto_post', 'al', false),
  ('al.f_role_code', 'al', false),
  ('al.f_user_id', 'al', false),
  ('al.f_ledger_type_code', 'al', false),
  ('al.f_timezone_code', 'al', false),
  ('al.f_country_code', 'al', false),
  ('al.f_locale', 'al', false),
  ('al.f_fiscal_year_start_month', 'al', false),
  ('al.v_expense', 'al', false),
  ('al.v_income', 'al', false),
  ('al.v_transfer', 'al', false),
  ('al.v_posted', 'al', false),
  ('al.v_pending', 'al', false),
  ('al.v_rule', 'al', false),
  ('al.v_manual', 'al', false),
  ('al.v_import', 'al', false),
  ('al.v_recurring', 'al', false),
  ('al.v_ai', 'al', false),
  ('al.v_monthly', 'al', false),
  ('al.v_weekly', 'al', false),
  ('al.v_daily', 'al', false),
  ('al.v_yearly', 'al', false),
  ('al.v_cash', 'al', false),
  ('al.v_bank', 'al', false),
  ('al.v_credit_card', 'al', false),
  ('al.v_e_wallet', 'al', false),
  ('al.v_investment', 'al', false),
  ('al.v_loan', 'al', false),
  ('al.v_other', 'al', false),
  ('al.v_active', 'al', false),
  ('al.v_left', 'al', false),
  ('al.v_removed', 'al', false)
on conflict (key) do nothing;

insert into public.translations (key, language_code, value) values
  ('lm.ledgerSettings', 'ja', '台帳の設定'), ('lm.ledgerSettings', 'vi', 'Cài đặt sổ'), ('lm.ledgerSettings', 'en', 'Ledger settings'),
  ('ls.title', 'ja', '台帳の設定'), ('ls.title', 'vi', 'Cài đặt sổ'), ('ls.title', 'en', 'Ledger settings'),
  ('ls.subtitle', 'ja', '台帳の基本情報。表示のみで、変えたいときに「編集」を押します。'), ('ls.subtitle', 'vi', 'Thông tin cơ bản của sổ — mặc định chỉ xem, bấm Sửa khi muốn thay đổi.'), ('ls.subtitle', 'en', 'The basics of this ledger — read-only until you choose to edit.'),
  ('ls.infoTitle', 'ja', '台帳の情報'), ('ls.infoTitle', 'vi', 'Thông tin sổ'), ('ls.infoTitle', 'en', 'Ledger details'),
  ('ls.infoSub', 'ja', '名前・通貨・地域・年度'), ('ls.infoSub', 'vi', 'Tên, tiền tệ, khu vực và năm tài chính'), ('ls.infoSub', 'en', 'Name, currency, region and fiscal year'),
  ('ls.infoEditSub', 'ja', '変更した項目には印が付きます。保存するまで反映されません。'), ('ls.infoEditSub', 'vi', 'Mục nào đổi sẽ được đánh dấu; chỉ áp dụng khi bấm Lưu.'), ('ls.infoEditSub', 'en', 'Changed fields are marked; nothing applies until you save.'),
  ('ls.owner', 'ja', 'オーナー'), ('ls.owner', 'vi', 'Chủ sổ'), ('ls.owner', 'en', 'Owner'),
  ('ls.created', 'ja', '作成日'), ('ls.created', 'vi', 'Ngày tạo'), ('ls.created', 'en', 'Created'),
  ('ls.rulesTitle', 'ja', '共有のルール'), ('ls.rulesTitle', 'vi', 'Quy tắc chia sẻ'), ('ls.rulesTitle', 'en', 'Sharing rules'),
  ('ls.related', 'ja', '関連ページ'), ('ls.related', 'vi', 'Trang liên quan'), ('ls.related', 'en', 'Related pages'),
  ('ls.linkMembers', 'ja', 'メンバーと権限'), ('ls.linkMembers', 'vi', 'Thành viên & quyền'), ('ls.linkMembers', 'en', 'Members & access'),
  ('ls.linkActivity', 'ja', '操作ログ'), ('ls.linkActivity', 'vi', 'Nhật ký hoạt động'), ('ls.linkActivity', 'en', 'Activity log'),
  ('ls.linkTexts', 'ja', '表示テキスト'), ('ls.linkTexts', 'vi', 'Văn bản giao diện'), ('ls.linkTexts', 'en', 'Interface texts'),
  ('ls.transferHint', 'ja', 'オーナーを譲るには、メンバーのページを開いてください。'), ('ls.transferHint', 'vi', 'Muốn chuyển quyền chủ sổ, hãy mở trang của thành viên đó.'), ('ls.transferHint', 'en', 'To hand over ownership, open that member''s page.'),
  ('ls.leaveSub', 'ja', 'この台帳から抜けます。あなたの記録は残ります。'), ('ls.leaveSub', 'vi', 'Rời khỏi sổ này; những gì bạn đã ghi vẫn được giữ lại.'), ('ls.leaveSub', 'en', 'Leave this ledger; what you recorded stays.'),
  ('al.title', 'ja', '操作ログ'), ('al.title', 'vi', 'Nhật ký hoạt động'), ('al.title', 'en', 'Activity log'),
  ('al.subtitle', 'ja', '台帳で誰が何をしたか。あなたが見られる記録だけが表示されます。'), ('al.subtitle', 'vi', 'Ai đã làm gì trong sổ — chỉ hiện những gì bạn được phép xem.'), ('al.subtitle', 'en', 'Who did what in the ledger — only what you are allowed to see.'),
  ('al.search', 'ja', '名前・店名で検索…'), ('al.search', 'vi', 'Tìm theo tên, cửa hàng…'), ('al.search', 'en', 'Search names, shops…'),
  ('al.period', 'ja', '期間'), ('al.period', 'vi', 'Khoảng thời gian'), ('al.period', 'en', 'Period'),
  ('al.lastDays', 'ja', '{{count}}日'), ('al.lastDays', 'vi', '{{count}} ngày'), ('al.lastDays', 'en', '{{count}} days'),
  ('al.allTime', 'ja', 'すべて'), ('al.allTime', 'vi', 'Tất cả'), ('al.allTime', 'en', 'All time'),
  ('al.allTypes', 'ja', 'すべて'), ('al.allTypes', 'vi', 'Tất cả'), ('al.allTypes', 'en', 'Everything'),
  ('al.e_transaction', 'ja', '取引'), ('al.e_transaction', 'vi', 'Giao dịch'), ('al.e_transaction', 'en', 'Transactions'),
  ('al.e_category', 'ja', 'カテゴリ'), ('al.e_category', 'vi', 'Danh mục'), ('al.e_category', 'en', 'Categories'),
  ('al.e_account', 'ja', '口座'), ('al.e_account', 'vi', 'Tài khoản'), ('al.e_account', 'en', 'Accounts'),
  ('al.e_budget', 'ja', '予算'), ('al.e_budget', 'vi', 'Ngân sách'), ('al.e_budget', 'en', 'Budgets'),
  ('al.e_category_rule', 'ja', 'ルール'), ('al.e_category_rule', 'vi', 'Quy tắc'), ('al.e_category_rule', 'en', 'Rules'),
  ('al.e_recurring', 'ja', '定期'), ('al.e_recurring', 'vi', 'Định kỳ'), ('al.e_recurring', 'en', 'Recurring'),
  ('al.e_member', 'ja', 'メンバー'), ('al.e_member', 'vi', 'Thành viên'), ('al.e_member', 'en', 'Members'),
  ('al.e_ledger', 'ja', '台帳'), ('al.e_ledger', 'vi', 'Sổ'), ('al.e_ledger', 'en', 'Ledger'),
  ('al.a_create', 'ja', '追加'), ('al.a_create', 'vi', 'Thêm'), ('al.a_create', 'en', 'Added'),
  ('al.a_update', 'ja', '変更'), ('al.a_update', 'vi', 'Sửa'), ('al.a_update', 'en', 'Changed'),
  ('al.a_delete', 'ja', '削除'), ('al.a_delete', 'vi', 'Xoá'), ('al.a_delete', 'en', 'Deleted'),
  ('al.k_create', 'ja', 'が追加：'), ('al.k_create', 'vi', 'đã thêm'), ('al.k_create', 'en', 'added'),
  ('al.k_update', 'ja', 'が変更：'), ('al.k_update', 'vi', 'đã sửa'), ('al.k_update', 'en', 'changed'),
  ('al.k_delete', 'ja', 'が削除：'), ('al.k_delete', 'vi', 'đã xoá'), ('al.k_delete', 'en', 'deleted'),
  ('al.k_restore', 'ja', 'が復元：'), ('al.k_restore', 'vi', 'đã khôi phục'), ('al.k_restore', 'en', 'restored'),
  ('al.clear', 'ja', '絞り込みを解除'), ('al.clear', 'vi', 'Xoá bộ lọc'), ('al.clear', 'en', 'Clear filters'),
  ('al.empty', 'ja', 'まだ記録がありません'), ('al.empty', 'vi', 'Chưa có hoạt động nào'), ('al.empty', 'en', 'No activity yet'),
  ('al.emptyFiltered', 'ja', '条件に合う記録がありません'), ('al.emptyFiltered', 'vi', 'Không có hoạt động nào khớp bộ lọc'), ('al.emptyFiltered', 'en', 'Nothing matches these filters'),
  ('al.today', 'ja', '今日'), ('al.today', 'vi', 'Hôm nay'), ('al.today', 'en', 'Today'),
  ('al.yesterday', 'ja', '昨日'), ('al.yesterday', 'vi', 'Hôm qua'), ('al.yesterday', 'en', 'Yesterday'),
  ('al.nEntries', 'ja', '{{count}} 件'), ('al.nEntries', 'vi', '{{count}} hoạt động'), ('al.nEntries', 'en', '{{count}} entries'),
  ('al.details', 'ja', '詳細（{{count}}）'), ('al.details', 'vi', 'Xem chi tiết ({{count}})'), ('al.details', 'en', 'Details ({{count}})'),
  ('al.hide', 'ja', '閉じる'), ('al.hide', 'vi', 'Thu gọn'), ('al.hide', 'en', 'Hide'),
  ('al.loadMore', 'ja', 'さらに読み込む'), ('al.loadMore', 'vi', 'Tải thêm'), ('al.loadMore', 'en', 'Load more'),
  ('al.privacyNote', 'ja', '他の人の非公開の記録は表示されません'), ('al.privacyNote', 'vi', 'Dữ liệu riêng tư của người khác không hiện ở đây'), ('al.privacyNote', 'en', 'Other people''s private records are not shown'),
  ('al.hiddenValue', 'ja', '（非公開）'), ('al.hiddenValue', 'vi', '(không xem được)'), ('al.hiddenValue', 'en', '(hidden)'),
  ('al.aRule', 'ja', 'ルール'), ('al.aRule', 'vi', 'một quy tắc'), ('al.aRule', 'en', 'a rule'),
  ('al.yes', 'ja', 'はい'), ('al.yes', 'vi', 'Có'), ('al.yes', 'en', 'Yes'),
  ('al.no', 'ja', 'いいえ'), ('al.no', 'vi', 'Không'), ('al.no', 'en', 'No'),
  ('al.f_amount', 'ja', '金額'), ('al.f_amount', 'vi', 'Số tiền'), ('al.f_amount', 'en', 'Amount'),
  ('al.f_transaction_date', 'ja', '日付'), ('al.f_transaction_date', 'vi', 'Ngày'), ('al.f_transaction_date', 'en', 'Date'),
  ('al.f_transaction_time', 'ja', '時刻'), ('al.f_transaction_time', 'vi', 'Giờ'), ('al.f_transaction_time', 'en', 'Time'),
  ('al.f_merchant_name', 'ja', '店名'), ('al.f_merchant_name', 'vi', 'Cửa hàng'), ('al.f_merchant_name', 'en', 'Shop'),
  ('al.f_description', 'ja', '内容'), ('al.f_description', 'vi', 'Nội dung'), ('al.f_description', 'en', 'Description'),
  ('al.f_notes', 'ja', 'メモ'), ('al.f_notes', 'vi', 'Ghi chú'), ('al.f_notes', 'en', 'Notes'),
  ('al.f_category_id', 'ja', 'カテゴリ'), ('al.f_category_id', 'vi', 'Danh mục'), ('al.f_category_id', 'en', 'Category'),
  ('al.f_account_id', 'ja', '口座'), ('al.f_account_id', 'vi', 'Tài khoản'), ('al.f_account_id', 'en', 'Account'),
  ('al.f_transfer_account_id', 'ja', '振替先'), ('al.f_transfer_account_id', 'vi', 'Tài khoản nhận'), ('al.f_transfer_account_id', 'en', 'Transfer to'),
  ('al.f_transaction_type', 'ja', '種類'), ('al.f_transaction_type', 'vi', 'Loại'), ('al.f_transaction_type', 'en', 'Type'),
  ('al.f_status', 'ja', '状態'), ('al.f_status', 'vi', 'Trạng thái'), ('al.f_status', 'en', 'Status'),
  ('al.f_paid_by_user_id', 'ja', '支払った人'), ('al.f_paid_by_user_id', 'vi', 'Người trả'), ('al.f_paid_by_user_id', 'en', 'Paid by'),
  ('al.f_categorized_by', 'ja', '分類方法'), ('al.f_categorized_by', 'vi', 'Cách phân loại'), ('al.f_categorized_by', 'en', 'Categorised by'),
  ('al.f_category_rule_id', 'ja', 'ルール'), ('al.f_category_rule_id', 'vi', 'Quy tắc'), ('al.f_category_rule_id', 'en', 'Rule'),
  ('al.f_needs_review', 'ja', '要確認'), ('al.f_needs_review', 'vi', 'Cần xem lại'), ('al.f_needs_review', 'en', 'Needs review'),
  ('al.f_exclude_from_reports', 'ja', '集計から除外'), ('al.f_exclude_from_reports', 'vi', 'Loại khỏi báo cáo'), ('al.f_exclude_from_reports', 'en', 'Left out of reports'),
  ('al.f_is_reconciled', 'ja', '照合済み'), ('al.f_is_reconciled', 'vi', 'Đã đối soát'), ('al.f_is_reconciled', 'en', 'Reconciled'),
  ('al.f_currency_code', 'ja', '通貨'), ('al.f_currency_code', 'vi', 'Tiền tệ'), ('al.f_currency_code', 'en', 'Currency'),
  ('al.f_name', 'ja', '名前'), ('al.f_name', 'vi', 'Tên'), ('al.f_name', 'en', 'Name'),
  ('al.f_parent_id', 'ja', '親カテゴリ'), ('al.f_parent_id', 'vi', 'Danh mục cha'), ('al.f_parent_id', 'en', 'Parent'),
  ('al.f_category_type', 'ja', '種類'), ('al.f_category_type', 'vi', 'Loại'), ('al.f_category_type', 'en', 'Type'),
  ('al.f_is_shared', 'ja', '共有'), ('al.f_is_shared', 'vi', 'Chia sẻ'), ('al.f_is_shared', 'en', 'Shared'),
  ('al.f_is_archived', 'ja', 'アーカイブ'), ('al.f_is_archived', 'vi', 'Lưu trữ'), ('al.f_is_archived', 'en', 'Archived'),
  ('al.f_color', 'ja', '色'), ('al.f_color', 'vi', 'Màu'), ('al.f_color', 'en', 'Colour'),
  ('al.f_owner_id', 'ja', 'オーナー'), ('al.f_owner_id', 'vi', 'Chủ'), ('al.f_owner_id', 'en', 'Owner'),
  ('al.f_account_type_code', 'ja', '口座の種類'), ('al.f_account_type_code', 'vi', 'Loại tài khoản'), ('al.f_account_type_code', 'en', 'Account type'),
  ('al.f_opening_balance', 'ja', '開始残高'), ('al.f_opening_balance', 'vi', 'Số dư đầu'), ('al.f_opening_balance', 'en', 'Opening balance'),
  ('al.f_opening_date', 'ja', '開始日'), ('al.f_opening_date', 'vi', 'Ngày bắt đầu'), ('al.f_opening_date', 'en', 'Opening date'),
  ('al.f_credit_limit', 'ja', '利用限度額'), ('al.f_credit_limit', 'vi', 'Hạn mức'), ('al.f_credit_limit', 'en', 'Credit limit'),
  ('al.f_institution_name', 'ja', '金融機関'), ('al.f_institution_name', 'vi', 'Ngân hàng / tổ chức'), ('al.f_institution_name', 'en', 'Institution'),
  ('al.f_account_number_last4', 'ja', '番号（下4桁）'), ('al.f_account_number_last4', 'vi', 'Số tài khoản (4 số cuối)'), ('al.f_account_number_last4', 'en', 'Number (last 4)'),
  ('al.f_include_in_net_worth', 'ja', '純資産に含める'), ('al.f_include_in_net_worth', 'vi', 'Tính vào tài sản'), ('al.f_include_in_net_worth', 'en', 'In net worth'),
  ('al.f_rollover', 'ja', '繰り越し'), ('al.f_rollover', 'vi', 'Cộng dồn'), ('al.f_rollover', 'en', 'Roll over'),
  ('al.f_warning_threshold_pct', 'ja', '警告ライン'), ('al.f_warning_threshold_pct', 'vi', 'Ngưỡng cảnh báo'), ('al.f_warning_threshold_pct', 'en', 'Warning at'),
  ('al.f_period_type', 'ja', '期間'), ('al.f_period_type', 'vi', 'Chu kỳ'), ('al.f_period_type', 'en', 'Period'),
  ('al.f_pattern', 'ja', 'キーワード'), ('al.f_pattern', 'vi', 'Từ khoá'), ('al.f_pattern', 'en', 'Keyword'),
  ('al.f_is_active', 'ja', '有効'), ('al.f_is_active', 'vi', 'Đang bật'), ('al.f_is_active', 'en', 'Active'),
  ('al.f_apply_on_import', 'ja', '取込時に適用'), ('al.f_apply_on_import', 'vi', 'Áp dụng khi nhập'), ('al.f_apply_on_import', 'en', 'Apply on import'),
  ('al.f_priority', 'ja', '優先度'), ('al.f_priority', 'vi', 'Độ ưu tiên'), ('al.f_priority', 'en', 'Priority'),
  ('al.f_frequency', 'ja', '頻度'), ('al.f_frequency', 'vi', 'Tần suất'), ('al.f_frequency', 'en', 'Frequency'),
  ('al.f_interval_count', 'ja', '間隔'), ('al.f_interval_count', 'vi', 'Khoảng cách'), ('al.f_interval_count', 'en', 'Every'),
  ('al.f_start_date', 'ja', '開始日'), ('al.f_start_date', 'vi', 'Ngày bắt đầu'), ('al.f_start_date', 'en', 'Starts'),
  ('al.f_end_date', 'ja', '終了日'), ('al.f_end_date', 'vi', 'Ngày kết thúc'), ('al.f_end_date', 'en', 'Ends'),
  ('al.f_day_of_month', 'ja', '日'), ('al.f_day_of_month', 'vi', 'Ngày trong tháng'), ('al.f_day_of_month', 'en', 'Day of month'),
  ('al.f_auto_post', 'ja', '自動で記録'), ('al.f_auto_post', 'vi', 'Tự ghi'), ('al.f_auto_post', 'en', 'Post automatically'),
  ('al.f_role_code', 'ja', '役割'), ('al.f_role_code', 'vi', 'Vai trò'), ('al.f_role_code', 'en', 'Role'),
  ('al.f_user_id', 'ja', 'メンバー'), ('al.f_user_id', 'vi', 'Thành viên'), ('al.f_user_id', 'en', 'Member'),
  ('al.f_ledger_type_code', 'ja', '台帳の種類'), ('al.f_ledger_type_code', 'vi', 'Loại sổ'), ('al.f_ledger_type_code', 'en', 'Ledger type'),
  ('al.f_timezone_code', 'ja', 'タイムゾーン'), ('al.f_timezone_code', 'vi', 'Múi giờ'), ('al.f_timezone_code', 'en', 'Time zone'),
  ('al.f_country_code', 'ja', '国'), ('al.f_country_code', 'vi', 'Quốc gia'), ('al.f_country_code', 'en', 'Country'),
  ('al.f_locale', 'ja', '表示形式'), ('al.f_locale', 'vi', 'Định dạng'), ('al.f_locale', 'en', 'Format'),
  ('al.f_fiscal_year_start_month', 'ja', '年度の開始月'), ('al.f_fiscal_year_start_month', 'vi', 'Tháng bắt đầu năm tài chính'), ('al.f_fiscal_year_start_month', 'en', 'Fiscal year starts'),
  ('al.v_expense', 'ja', '支出'), ('al.v_expense', 'vi', 'Chi'), ('al.v_expense', 'en', 'Expense'),
  ('al.v_income', 'ja', '収入'), ('al.v_income', 'vi', 'Thu'), ('al.v_income', 'en', 'Income'),
  ('al.v_transfer', 'ja', '振替'), ('al.v_transfer', 'vi', 'Chuyển khoản'), ('al.v_transfer', 'en', 'Transfer'),
  ('al.v_posted', 'ja', '確定'), ('al.v_posted', 'vi', 'Đã ghi'), ('al.v_posted', 'en', 'Posted'),
  ('al.v_pending', 'ja', '保留'), ('al.v_pending', 'vi', 'Đang chờ'), ('al.v_pending', 'en', 'Pending'),
  ('al.v_rule', 'ja', 'ルール'), ('al.v_rule', 'vi', 'Quy tắc'), ('al.v_rule', 'en', 'Rule'),
  ('al.v_manual', 'ja', '手動'), ('al.v_manual', 'vi', 'Thủ công'), ('al.v_manual', 'en', 'Manual'),
  ('al.v_import', 'ja', '取込'), ('al.v_import', 'vi', 'Nhập file'), ('al.v_import', 'en', 'Import'),
  ('al.v_recurring', 'ja', '定期'), ('al.v_recurring', 'vi', 'Định kỳ'), ('al.v_recurring', 'en', 'Recurring'),
  ('al.v_ai', 'ja', 'AI'), ('al.v_ai', 'vi', 'AI'), ('al.v_ai', 'en', 'AI'),
  ('al.v_monthly', 'ja', '毎月'), ('al.v_monthly', 'vi', 'Hằng tháng'), ('al.v_monthly', 'en', 'Monthly'),
  ('al.v_weekly', 'ja', '毎週'), ('al.v_weekly', 'vi', 'Hằng tuần'), ('al.v_weekly', 'en', 'Weekly'),
  ('al.v_daily', 'ja', '毎日'), ('al.v_daily', 'vi', 'Hằng ngày'), ('al.v_daily', 'en', 'Daily'),
  ('al.v_yearly', 'ja', '毎年'), ('al.v_yearly', 'vi', 'Hằng năm'), ('al.v_yearly', 'en', 'Yearly'),
  ('al.v_cash', 'ja', '現金'), ('al.v_cash', 'vi', 'Tiền mặt'), ('al.v_cash', 'en', 'Cash'),
  ('al.v_bank', 'ja', '銀行'), ('al.v_bank', 'vi', 'Ngân hàng'), ('al.v_bank', 'en', 'Bank'),
  ('al.v_credit_card', 'ja', 'クレジットカード'), ('al.v_credit_card', 'vi', 'Thẻ tín dụng'), ('al.v_credit_card', 'en', 'Credit card'),
  ('al.v_e_wallet', 'ja', '電子マネー'), ('al.v_e_wallet', 'vi', 'Ví điện tử'), ('al.v_e_wallet', 'en', 'E-wallet'),
  ('al.v_investment', 'ja', '投資'), ('al.v_investment', 'vi', 'Đầu tư'), ('al.v_investment', 'en', 'Investment'),
  ('al.v_loan', 'ja', 'ローン'), ('al.v_loan', 'vi', 'Khoản vay'), ('al.v_loan', 'en', 'Loan'),
  ('al.v_other', 'ja', 'その他'), ('al.v_other', 'vi', 'Khác'), ('al.v_other', 'en', 'Other'),
  ('al.v_active', 'ja', '参加中'), ('al.v_active', 'vi', 'Đang tham gia'), ('al.v_active', 'en', 'Active'),
  ('al.v_left', 'ja', '退出'), ('al.v_left', 'vi', 'Đã rời'), ('al.v_left', 'en', 'Left'),
  ('al.v_removed', 'ja', '削除済み'), ('al.v_removed', 'vi', 'Đã gỡ'), ('al.v_removed', 'en', 'Removed')
on conflict (key, language_code) do update set value = excluded.value, updated_at = now();
