-- Notifications filters/detail + tx errors
-- (fresh databases get these from the 0016 seed).
insert into public.translation_keys (key, namespace, is_user_editable) values
  ('notifications.fAll', 'notifications', false),
  ('notifications.fOther', 'notifications', false),
  ('notifications.timeAny', 'notifications', false),
  ('notifications.timeToday', 'notifications', false),
  ('notifications.time7', 'notifications', false),
  ('notifications.time30', 'notifications', false),
  ('notifications.timeMonth', 'notifications', false),
  ('notifications.actorAll', 'notifications', false),
  ('notifications.unreadOnly', 'notifications', false),
  ('notifications.dayToday', 'notifications', false),
  ('notifications.dayYesterday', 'notifications', false),
  ('notifications.emptyFiltered', 'notifications', false),
  ('notifications.clearFilters', 'notifications', false),
  ('notifications.filterTime', 'notifications', false),
  ('notifications.filterActor', 'notifications', false),
  ('notifications.filterKind', 'notifications', false),
  ('notifications.detailTitle', 'notifications', false),
  ('notifications.who', 'notifications', false),
  ('notifications.when', 'notifications', false),
  ('notifications.kind', 'notifications', false),
  ('notifications.ledger', 'notifications', false),
  ('notifications.changes', 'notifications', false),
  ('notifications.created', 'notifications', false),
  ('notifications.deletedTx', 'notifications', false),
  ('notifications.deletedBadge', 'notifications', false),
  ('notifications.openTx', 'notifications', false),
  ('notifications.openCategory', 'notifications', false),
  ('notifications.openApproval', 'notifications', false),
  ('notifications.open', 'notifications', false),
  ('notifications.noChanges', 'notifications', false),
  ('notifications.txCount', 'notifications', false),
  ('notifications.system', 'notifications', false),
  ('notifications.byName', 'notifications', false),
  ('notifications.filters', 'notifications', false),
  ('txform.errorCategoryAccess', 'txform', false),
  ('txform.errorNoPermission', 'txform', false)
on conflict (key) do nothing;

insert into public.translations (key, language_code, value) values
  ('notifications.fAll', 'ja', 'すべて'), ('notifications.fAll', 'vi', 'Tất cả'), ('notifications.fAll', 'en', 'All'),
  ('notifications.fOther', 'ja', 'その他'), ('notifications.fOther', 'vi', 'Khác'), ('notifications.fOther', 'en', 'Other'),
  ('notifications.timeAny', 'ja', '全期間'), ('notifications.timeAny', 'vi', 'Mọi lúc'), ('notifications.timeAny', 'en', 'Any time'),
  ('notifications.timeToday', 'ja', '今日'), ('notifications.timeToday', 'vi', 'Hôm nay'), ('notifications.timeToday', 'en', 'Today'),
  ('notifications.time7', 'ja', '過去7日'), ('notifications.time7', 'vi', '7 ngày qua'), ('notifications.time7', 'en', 'Last 7 days'),
  ('notifications.time30', 'ja', '過去30日'), ('notifications.time30', 'vi', '30 ngày qua'), ('notifications.time30', 'en', 'Last 30 days'),
  ('notifications.timeMonth', 'ja', '今月'), ('notifications.timeMonth', 'vi', 'Tháng này'), ('notifications.timeMonth', 'en', 'This month'),
  ('notifications.actorAll', 'ja', '全員'), ('notifications.actorAll', 'vi', 'Mọi người'), ('notifications.actorAll', 'en', 'Everyone'),
  ('notifications.unreadOnly', 'ja', '未読のみ'), ('notifications.unreadOnly', 'vi', 'Chỉ chưa đọc'), ('notifications.unreadOnly', 'en', 'Unread only'),
  ('notifications.dayToday', 'ja', '今日'), ('notifications.dayToday', 'vi', 'Hôm nay'), ('notifications.dayToday', 'en', 'Today'),
  ('notifications.dayYesterday', 'ja', '昨日'), ('notifications.dayYesterday', 'vi', 'Hôm qua'), ('notifications.dayYesterday', 'en', 'Yesterday'),
  ('notifications.emptyFiltered', 'ja', '条件に合う通知はありません'), ('notifications.emptyFiltered', 'vi', 'Không có thông báo nào khớp bộ lọc'), ('notifications.emptyFiltered', 'en', 'No notifications match'),
  ('notifications.clearFilters', 'ja', '絞り込みをクリア'), ('notifications.clearFilters', 'vi', 'Bỏ lọc'), ('notifications.clearFilters', 'en', 'Clear filters'),
  ('notifications.filterTime', 'ja', '期間'), ('notifications.filterTime', 'vi', 'Thời gian'), ('notifications.filterTime', 'en', 'Time'),
  ('notifications.filterActor', 'ja', '実行者'), ('notifications.filterActor', 'vi', 'Người thực hiện'), ('notifications.filterActor', 'en', 'By'),
  ('notifications.filterKind', 'ja', '種類'), ('notifications.filterKind', 'vi', 'Loại'), ('notifications.filterKind', 'en', 'Kind'),
  ('notifications.detailTitle', 'ja', '通知の詳細'), ('notifications.detailTitle', 'vi', 'Chi tiết thông báo'), ('notifications.detailTitle', 'en', 'Notification details'),
  ('notifications.who', 'ja', '実行者'), ('notifications.who', 'vi', 'Người thực hiện'), ('notifications.who', 'en', 'By'),
  ('notifications.when', 'ja', '日時'), ('notifications.when', 'vi', 'Thời gian'), ('notifications.when', 'en', 'When'),
  ('notifications.kind', 'ja', '種類'), ('notifications.kind', 'vi', 'Loại'), ('notifications.kind', 'en', 'Kind'),
  ('notifications.ledger', 'ja', '台帳'), ('notifications.ledger', 'vi', 'Sổ'), ('notifications.ledger', 'en', 'Ledger'),
  ('notifications.changes', 'ja', '変更内容'), ('notifications.changes', 'vi', 'Thay đổi'), ('notifications.changes', 'en', 'Changes'),
  ('notifications.created', 'ja', '追加'), ('notifications.created', 'vi', 'Đã thêm'), ('notifications.created', 'en', 'Added'),
  ('notifications.deletedTx', 'ja', '削除された取引'), ('notifications.deletedTx', 'vi', 'Giao dịch đã bị xoá'), ('notifications.deletedTx', 'en', 'Deleted transaction'),
  ('notifications.deletedBadge', 'ja', '削除済み'), ('notifications.deletedBadge', 'vi', 'Đã xoá'), ('notifications.deletedBadge', 'en', 'Deleted'),
  ('notifications.openTx', 'ja', '取引を表示'), ('notifications.openTx', 'vi', 'Xem giao dịch'), ('notifications.openTx', 'en', 'Open transaction'),
  ('notifications.openCategory', 'ja', 'カテゴリを表示'), ('notifications.openCategory', 'vi', 'Xem danh mục'), ('notifications.openCategory', 'en', 'Open category'),
  ('notifications.openApproval', 'ja', '承認画面を開く'), ('notifications.openApproval', 'vi', 'Mở phê duyệt'), ('notifications.openApproval', 'en', 'Open approvals'),
  ('notifications.open', 'ja', '開く'), ('notifications.open', 'vi', 'Mở'), ('notifications.open', 'en', 'Open'),
  ('notifications.noChanges', 'ja', '変更の詳細はありません'), ('notifications.noChanges', 'vi', 'Không có chi tiết thay đổi'), ('notifications.noChanges', 'en', 'No change details'),
  ('notifications.txCount', 'ja', '{{count}} 件の取引'), ('notifications.txCount', 'vi', '{{count}} giao dịch'), ('notifications.txCount', 'en', '{{count}} transactions'),
  ('notifications.system', 'ja', 'システム'), ('notifications.system', 'vi', 'Hệ thống'), ('notifications.system', 'en', 'System'),
  ('notifications.byName', 'ja', '{{name}} さん'), ('notifications.byName', 'vi', 'Bởi {{name}}'), ('notifications.byName', 'en', 'By {{name}}'),
  ('notifications.filters', 'ja', '絞り込み'), ('notifications.filters', 'vi', 'Bộ lọc'), ('notifications.filters', 'en', 'Filters'),
  ('txform.errorCategoryAccess', 'ja', 'このカテゴリは他の人のもので、あなたとは共有されていません。'), ('txform.errorCategoryAccess', 'vi', 'Danh mục này của người khác và chưa được chia sẻ với bạn.'), ('txform.errorCategoryAccess', 'en', 'That category belongs to someone else and is not shared with you.'),
  ('txform.errorNoPermission', 'ja', 'この取引を変更する権限がありません。'), ('txform.errorNoPermission', 'vi', 'Bạn không có quyền thay đổi giao dịch này.'), ('txform.errorNoPermission', 'en', 'You can''t change this transaction.')
on conflict (key, language_code) do update set value = excluded.value, updated_at = now();
