-- Approvals, proposals, history and push texts
-- (fresh databases get these from the 0016 seed).
insert into public.translation_keys (key, namespace, is_user_editable) values
  ('approvals.title', 'approvals', false),
  ('approvals.subtitle', 'approvals', false),
  ('approvals.tabInbox', 'approvals', false),
  ('approvals.tabSent', 'approvals', false),
  ('approvals.tabDone', 'approvals', false),
  ('approvals.emptyInbox', 'approvals', false),
  ('approvals.emptyInboxSub', 'approvals', false),
  ('approvals.emptySent', 'approvals', false),
  ('approvals.emptyDone', 'approvals', false),
  ('approvals.approve', 'approvals', false),
  ('approvals.reject', 'approvals', false),
  ('approvals.approveAll', 'approvals', false),
  ('approvals.cancel', 'approvals', false),
  ('approvals.cancelConfirm', 'approvals', false),
  ('approvals.rejectTitle', 'approvals', false),
  ('approvals.rejectReason', 'approvals', false),
  ('approvals.approveAllTitle', 'approvals', false),
  ('approvals.approveAllMsg', 'approvals', false),
  ('approvals.doneApproved', 'approvals', false),
  ('approvals.doneApprovedN', 'approvals', false),
  ('approvals.doneRejected', 'approvals', false),
  ('approvals.doneCancelled', 'approvals', false),
  ('approvals.doneObsolete', 'approvals', false),
  ('approvals.statusPending', 'approvals', false),
  ('approvals.statusApproved', 'approvals', false),
  ('approvals.statusRejected', 'approvals', false),
  ('approvals.statusCancelled', 'approvals', false),
  ('approvals.statusObsolete', 'approvals', false),
  ('approvals.proposedBy', 'approvals', false),
  ('approvals.reviewedBy', 'approvals', false),
  ('approvals.to', 'approvals', false),
  ('approvals.note', 'approvals', false),
  ('approvals.reason', 'approvals', false),
  ('approvals.current', 'approvals', false),
  ('approvals.proposed', 'approvals', false),
  ('approvals.changedSince', 'approvals', false),
  ('approvals.openCategory', 'approvals', false),
  ('approvals.actSubcategoryCreate', 'approvals', false),
  ('approvals.actCategoryUpdate', 'approvals', false),
  ('approvals.actCategoryDelete', 'approvals', false),
  ('approvals.actBudgetSet', 'approvals', false),
  ('approvals.actKeywordAdd', 'approvals', false),
  ('approvals.actKeywordRemove', 'approvals', false),
  ('approvals.actRuleCreate', 'approvals', false),
  ('approvals.actRuleToggle', 'approvals', false),
  ('approvals.fieldName', 'approvals', false),
  ('approvals.fieldIcon', 'approvals', false),
  ('approvals.fieldColor', 'approvals', false),
  ('approvals.fieldDescription', 'approvals', false),
  ('approvals.fieldAmount', 'approvals', false),
  ('approvals.fieldPattern', 'approvals', false),
  ('approvals.fieldMatch', 'approvals', false),
  ('approvals.fieldIsActive', 'approvals', false),
  ('approvals.on', 'approvals', false),
  ('approvals.off', 'approvals', false),
  ('approvals.none', 'approvals', false),
  ('approvals.proposeBanner', 'approvals', false),
  ('approvals.sent', 'approvals', false),
  ('approvals.sentSub', 'approvals', false),
  ('approvals.pendingMine', 'approvals', false),
  ('approvals.pendingOwner', 'approvals', false),
  ('approvals.review', 'approvals', false),
  ('approvals.view', 'approvals', false),
  ('approvals.pendingChip', 'approvals', false),
  ('approvals.pendingDelete', 'approvals', false),
  ('approvals.pendingBudget', 'approvals', false),
  ('approvals.proposeSubmit', 'approvals', false),
  ('approvals.proposeFormHint', 'approvals', false),
  ('approvals.proposeLocked', 'approvals', false),
  ('approvals.proposeDeleteTitle', 'approvals', false),
  ('approvals.proposeDeleteMsg', 'approvals', false),
  ('approvals.errNoChange', 'approvals', false),
  ('approvals.errTaken', 'approvals', false),
  ('approvals.errAlready', 'approvals', false),
  ('approvals.errRootLocked', 'approvals', false),
  ('approvals.errNoPermission', 'approvals', false),
  ('approvals.errGone', 'approvals', false),
  ('approvals.errReviewed', 'approvals', false),
  ('approvals.tabHistory', 'approvals', false),
  ('approvals.histTitle', 'approvals', false),
  ('approvals.histSub', 'approvals', false),
  ('approvals.histEmpty', 'approvals', false),
  ('approvals.histMore', 'approvals', false),
  ('approvals.histTxCreate', 'approvals', false),
  ('approvals.histTxUpdate', 'approvals', false),
  ('approvals.histTxDelete', 'approvals', false),
  ('approvals.histCatCreate', 'approvals', false),
  ('approvals.histCatUpdate', 'approvals', false),
  ('approvals.histCatDelete', 'approvals', false),
  ('approvals.histBudgetCreate', 'approvals', false),
  ('approvals.histBudgetUpdate', 'approvals', false),
  ('approvals.histBudgetDelete', 'approvals', false),
  ('approvals.histRuleCreate', 'approvals', false),
  ('approvals.histRuleUpdate', 'approvals', false),
  ('approvals.histRuleDelete', 'approvals', false),
  ('approvals.histProposed', 'approvals', false),
  ('approvals.histApprovedBy', 'approvals', false),
  ('approvals.histRejectedBy', 'approvals', false),
  ('approvals.histSystem', 'approvals', false),
  ('approvals.fAmount', 'approvals', false),
  ('approvals.fDate', 'approvals', false),
  ('approvals.fCategory', 'approvals', false),
  ('approvals.fAccount', 'approvals', false),
  ('approvals.fNotes', 'approvals', false),
  ('approvals.fPaidBy', 'approvals', false),
  ('approvals.fStatus', 'approvals', false),
  ('approvals.fType', 'approvals', false),
  ('approvals.fMerchant', 'approvals', false),
  ('approvals.fShared', 'approvals', false),
  ('approvals.fOwner', 'approvals', false),
  ('approvals.navBadge', 'approvals', false),
  ('approvals.pushTitle', 'approvals', false),
  ('approvals.pushOff', 'approvals', false),
  ('approvals.pushOn', 'approvals', false),
  ('approvals.pushEnable', 'approvals', false),
  ('approvals.pushDisable', 'approvals', false),
  ('approvals.pushEnabled', 'approvals', false),
  ('approvals.pushDisabled', 'approvals', false),
  ('approvals.pushDenied', 'approvals', false),
  ('approvals.pushUnsupported', 'approvals', false),
  ('approvals.pushNotConfigured', 'approvals', false),
  ('approvals.live', 'approvals', false)
on conflict (key) do nothing;

insert into public.translations (key, language_code, value) values
  ('approvals.title', 'ja', '承認'), ('approvals.title', 'vi', 'Phê duyệt'), ('approvals.title', 'en', 'Approvals'),
  ('approvals.subtitle', 'ja', '共有カテゴリへの変更提案'), ('approvals.subtitle', 'vi', 'Đề xuất thay đổi trên các danh mục được chia sẻ'), ('approvals.subtitle', 'en', 'Proposed changes to shared categories'),
  ('approvals.tabInbox', 'ja', '承認待ち'), ('approvals.tabInbox', 'vi', 'Cần tôi duyệt'), ('approvals.tabInbox', 'en', 'To review'),
  ('approvals.tabSent', 'ja', '自分の提案'), ('approvals.tabSent', 'vi', 'Tôi đã gửi'), ('approvals.tabSent', 'en', 'Sent by me'),
  ('approvals.tabDone', 'ja', '処理済み'), ('approvals.tabDone', 'vi', 'Đã xử lý'), ('approvals.tabDone', 'en', 'Done'),
  ('approvals.emptyInbox', 'ja', '承認待ちの提案はありません'), ('approvals.emptyInbox', 'vi', 'Không có đề xuất nào cần duyệt'), ('approvals.emptyInbox', 'en', 'Nothing to review'),
  ('approvals.emptyInboxSub', 'ja', '共有したメンバーが予算・サブカテゴリ・キーワード・ルールを変更すると、ここに届きます。'), ('approvals.emptyInboxSub', 'vi', 'Khi người được chia sẻ sửa ngân sách, nhóm con, từ khoá hay quy tắc, đề xuất sẽ hiện ở đây.'), ('approvals.emptyInboxSub', 'en', 'When people you share with change a budget, sub-category, keyword or rule, it shows up here.'),
  ('approvals.emptySent', 'ja', 'まだ提案していません'), ('approvals.emptySent', 'vi', 'Bạn chưa gửi đề xuất nào'), ('approvals.emptySent', 'en', 'You haven''t proposed anything yet'),
  ('approvals.emptyDone', 'ja', '処理済みの提案はありません'), ('approvals.emptyDone', 'vi', 'Chưa có đề xuất nào được xử lý'), ('approvals.emptyDone', 'en', 'Nothing handled yet'),
  ('approvals.approve', 'ja', '承認'), ('approvals.approve', 'vi', 'Duyệt'), ('approvals.approve', 'en', 'Approve'),
  ('approvals.reject', 'ja', '却下'), ('approvals.reject', 'vi', 'Từ chối'), ('approvals.reject', 'en', 'Decline'),
  ('approvals.approveAll', 'ja', 'すべて承認（{{count}}）'), ('approvals.approveAll', 'vi', 'Duyệt tất cả ({{count}})'), ('approvals.approveAll', 'en', 'Approve all ({{count}})'),
  ('approvals.cancel', 'ja', '提案を取り消す'), ('approvals.cancel', 'vi', 'Huỷ đề xuất'), ('approvals.cancel', 'en', 'Withdraw'),
  ('approvals.cancelConfirm', 'ja', 'この提案を取り消しますか？'), ('approvals.cancelConfirm', 'vi', 'Huỷ đề xuất này?'), ('approvals.cancelConfirm', 'en', 'Withdraw this proposal?'),
  ('approvals.rejectTitle', 'ja', 'この提案を却下しますか？'), ('approvals.rejectTitle', 'vi', 'Từ chối đề xuất này?'), ('approvals.rejectTitle', 'en', 'Decline this proposal?'),
  ('approvals.rejectReason', 'ja', '理由（任意）— 提案者に伝わります'), ('approvals.rejectReason', 'vi', 'Lý do (không bắt buộc) — người đề xuất sẽ thấy'), ('approvals.rejectReason', 'en', 'Reason (optional) — the proposer will see it'),
  ('approvals.approveAllTitle', 'ja', '{{count}} 件の提案をすべて承認しますか？'), ('approvals.approveAllTitle', 'vi', 'Duyệt cả {{count}} đề xuất?'), ('approvals.approveAllTitle', 'en', 'Approve all {{count}} proposals?'),
  ('approvals.approveAllMsg', 'ja', '承認するとすぐに反映されます。'), ('approvals.approveAllMsg', 'vi', 'Các thay đổi sẽ được áp dụng ngay.'), ('approvals.approveAllMsg', 'en', 'The changes take effect right away.'),
  ('approvals.doneApproved', 'ja', '承認して反映しました'), ('approvals.doneApproved', 'vi', 'Đã duyệt và áp dụng'), ('approvals.doneApproved', 'en', 'Approved and applied'),
  ('approvals.doneApprovedN', 'ja', '{{count}} 件を承認しました'), ('approvals.doneApprovedN', 'vi', 'Đã duyệt {{count}} đề xuất'), ('approvals.doneApprovedN', 'en', 'Approved {{count}} proposals'),
  ('approvals.doneRejected', 'ja', '却下しました'), ('approvals.doneRejected', 'vi', 'Đã từ chối'), ('approvals.doneRejected', 'en', 'Declined'),
  ('approvals.doneCancelled', 'ja', '提案を取り消しました'), ('approvals.doneCancelled', 'vi', 'Đã huỷ đề xuất'), ('approvals.doneCancelled', 'en', 'Proposal withdrawn'),
  ('approvals.doneObsolete', 'ja', '対象が変更・削除されたため適用できませんでした'), ('approvals.doneObsolete', 'vi', 'Không áp dụng được: mục đã bị thay đổi hoặc xoá'), ('approvals.doneObsolete', 'en', 'Could not apply: the item was changed or deleted'),
  ('approvals.statusPending', 'ja', '承認待ち'), ('approvals.statusPending', 'vi', 'Chờ duyệt'), ('approvals.statusPending', 'en', 'Pending'),
  ('approvals.statusApproved', 'ja', '承認済み'), ('approvals.statusApproved', 'vi', 'Đã duyệt'), ('approvals.statusApproved', 'en', 'Approved'),
  ('approvals.statusRejected', 'ja', '却下'), ('approvals.statusRejected', 'vi', 'Đã từ chối'), ('approvals.statusRejected', 'en', 'Declined'),
  ('approvals.statusCancelled', 'ja', '取り消し'), ('approvals.statusCancelled', 'vi', 'Đã huỷ'), ('approvals.statusCancelled', 'en', 'Withdrawn'),
  ('approvals.statusObsolete', 'ja', '適用不可'), ('approvals.statusObsolete', 'vi', 'Không còn áp dụng'), ('approvals.statusObsolete', 'en', 'No longer applies'),
  ('approvals.proposedBy', 'ja', '{{name}} さんの提案'), ('approvals.proposedBy', 'vi', '{{name}} đề xuất'), ('approvals.proposedBy', 'en', 'Proposed by {{name}}'),
  ('approvals.reviewedBy', 'ja', '{{name}} · {{time}}'), ('approvals.reviewedBy', 'vi', '{{name}} · {{time}}'), ('approvals.reviewedBy', 'en', '{{name}} · {{time}}'),
  ('approvals.to', 'ja', '宛先：{{name}}'), ('approvals.to', 'vi', 'Gửi {{name}} duyệt'), ('approvals.to', 'en', 'For {{name}}'),
  ('approvals.note', 'ja', 'メモ'), ('approvals.note', 'vi', 'Ghi chú'), ('approvals.note', 'en', 'Note'),
  ('approvals.reason', 'ja', '理由'), ('approvals.reason', 'vi', 'Lý do'), ('approvals.reason', 'en', 'Reason'),
  ('approvals.current', 'ja', '現在'), ('approvals.current', 'vi', 'Hiện tại'), ('approvals.current', 'en', 'Now'),
  ('approvals.proposed', 'ja', '提案'), ('approvals.proposed', 'vi', 'Đề xuất'), ('approvals.proposed', 'en', 'Proposed'),
  ('approvals.changedSince', 'ja', '提案後に変更されています'), ('approvals.changedSince', 'vi', 'Đã thay đổi kể từ khi đề xuất'), ('approvals.changedSince', 'en', 'Changed since proposed'),
  ('approvals.openCategory', 'ja', 'カテゴリを開く'), ('approvals.openCategory', 'vi', 'Mở danh mục'), ('approvals.openCategory', 'en', 'Open category'),
  ('approvals.actSubcategoryCreate', 'ja', 'サブカテゴリを追加'), ('approvals.actSubcategoryCreate', 'vi', 'Thêm nhóm con'), ('approvals.actSubcategoryCreate', 'en', 'Add sub-category'),
  ('approvals.actCategoryUpdate', 'ja', 'サブカテゴリを編集'), ('approvals.actCategoryUpdate', 'vi', 'Sửa nhóm con'), ('approvals.actCategoryUpdate', 'en', 'Edit sub-category'),
  ('approvals.actCategoryDelete', 'ja', 'サブカテゴリを削除'), ('approvals.actCategoryDelete', 'vi', 'Xoá nhóm con'), ('approvals.actCategoryDelete', 'en', 'Delete sub-category'),
  ('approvals.actBudgetSet', 'ja', '予算を変更'), ('approvals.actBudgetSet', 'vi', 'Đổi ngân sách'), ('approvals.actBudgetSet', 'en', 'Change budget'),
  ('approvals.actKeywordAdd', 'ja', 'キーワードを追加'), ('approvals.actKeywordAdd', 'vi', 'Thêm từ khoá'), ('approvals.actKeywordAdd', 'en', 'Add keyword'),
  ('approvals.actKeywordRemove', 'ja', 'キーワードを削除'), ('approvals.actKeywordRemove', 'vi', 'Xoá từ khoá'), ('approvals.actKeywordRemove', 'en', 'Remove keyword'),
  ('approvals.actRuleCreate', 'ja', 'ルールを追加'), ('approvals.actRuleCreate', 'vi', 'Thêm quy tắc'), ('approvals.actRuleCreate', 'en', 'Add rule'),
  ('approvals.actRuleToggle', 'ja', 'ルールのオン/オフ'), ('approvals.actRuleToggle', 'vi', 'Bật/tắt quy tắc'), ('approvals.actRuleToggle', 'en', 'Turn rule on/off'),
  ('approvals.fieldName', 'ja', '名前'), ('approvals.fieldName', 'vi', 'Tên'), ('approvals.fieldName', 'en', 'Name'),
  ('approvals.fieldIcon', 'ja', 'アイコン'), ('approvals.fieldIcon', 'vi', 'Biểu tượng'), ('approvals.fieldIcon', 'en', 'Icon'),
  ('approvals.fieldColor', 'ja', '色'), ('approvals.fieldColor', 'vi', 'Màu'), ('approvals.fieldColor', 'en', 'Colour'),
  ('approvals.fieldDescription', 'ja', '説明'), ('approvals.fieldDescription', 'vi', 'Mô tả'), ('approvals.fieldDescription', 'en', 'Description'),
  ('approvals.fieldAmount', 'ja', '月の予算'), ('approvals.fieldAmount', 'vi', 'Ngân sách / tháng'), ('approvals.fieldAmount', 'en', 'Monthly budget'),
  ('approvals.fieldPattern', 'ja', 'キーワード'), ('approvals.fieldPattern', 'vi', 'Từ khoá'), ('approvals.fieldPattern', 'en', 'Keyword'),
  ('approvals.fieldMatch', 'ja', '条件'), ('approvals.fieldMatch', 'vi', 'Điều kiện'), ('approvals.fieldMatch', 'en', 'Condition'),
  ('approvals.fieldIsActive', 'ja', '状態'), ('approvals.fieldIsActive', 'vi', 'Trạng thái'), ('approvals.fieldIsActive', 'en', 'State'),
  ('approvals.on', 'ja', 'オン'), ('approvals.on', 'vi', 'Bật'), ('approvals.on', 'en', 'On'),
  ('approvals.off', 'ja', 'オフ'), ('approvals.off', 'vi', 'Tắt'), ('approvals.off', 'en', 'Off'),
  ('approvals.none', 'ja', 'なし'), ('approvals.none', 'vi', 'Không có'), ('approvals.none', 'en', 'None'),
  ('approvals.proposeBanner', 'ja', 'このカテゴリは {{owner}} さんのものです。予算・サブカテゴリ・キーワード・ルールの変更は {{owner}} さんの承認後に反映されます。'), ('approvals.proposeBanner', 'vi', 'Danh mục này của {{owner}}. Thay đổi về ngân sách, nhóm con, từ khoá và quy tắc sẽ được gửi để {{owner}} duyệt rồi mới áp dụng.'), ('approvals.proposeBanner', 'en', 'This category belongs to {{owner}}. Changes to budgets, sub-categories, keywords and rules apply once {{owner}} approves them.'),
  ('approvals.sent', 'ja', '提案を送信しました · {{owner}} さんの承認待ち'), ('approvals.sent', 'vi', 'Đã gửi đề xuất · chờ {{owner}} duyệt'), ('approvals.sent', 'en', 'Proposal sent · waiting for {{owner}}'),
  ('approvals.sentSub', 'ja', '承認されると通知が届きます。'), ('approvals.sentSub', 'vi', 'Bạn sẽ nhận thông báo khi được duyệt.'), ('approvals.sentSub', 'en', 'You''ll be notified when it''s decided.'),
  ('approvals.pendingMine', 'ja', '{{count}} 件の提案が承認待ちです'), ('approvals.pendingMine', 'vi', '{{count}} đề xuất của bạn đang chờ duyệt'), ('approvals.pendingMine', 'en', '{{count}} of your proposals are waiting'),
  ('approvals.pendingOwner', 'ja', '{{count}} 件の変更提案が承認待ちです'), ('approvals.pendingOwner', 'vi', 'Có {{count}} đề xuất thay đổi cần bạn duyệt'), ('approvals.pendingOwner', 'en', '{{count}} proposed changes need your review'),
  ('approvals.review', 'ja', '確認する'), ('approvals.review', 'vi', 'Xem & duyệt'), ('approvals.review', 'en', 'Review'),
  ('approvals.view', 'ja', '表示'), ('approvals.view', 'vi', 'Xem'), ('approvals.view', 'en', 'View'),
  ('approvals.pendingChip', 'ja', '承認待ち'), ('approvals.pendingChip', 'vi', 'Chờ duyệt'), ('approvals.pendingChip', 'en', 'Pending'),
  ('approvals.pendingDelete', 'ja', '削除を提案中'), ('approvals.pendingDelete', 'vi', 'Đang đề xuất xoá'), ('approvals.pendingDelete', 'en', 'Deletion proposed'),
  ('approvals.pendingBudget', 'ja', '{{amount}} を提案中'), ('approvals.pendingBudget', 'vi', 'Đề xuất {{amount}}'), ('approvals.pendingBudget', 'en', 'Proposed {{amount}}'),
  ('approvals.proposeSubmit', 'ja', '提案を送信'), ('approvals.proposeSubmit', 'vi', 'Gửi đề xuất'), ('approvals.proposeSubmit', 'en', 'Send proposal'),
  ('approvals.proposeFormHint', 'ja', '{{owner}} さんが承認すると反映されます。'), ('approvals.proposeFormHint', 'vi', 'Thay đổi sẽ được áp dụng sau khi {{owner}} duyệt.'), ('approvals.proposeFormHint', 'en', 'Applies once {{owner}} approves.'),
  ('approvals.proposeLocked', 'ja', '名前・アイコン・色は {{owner}} さんのみ変更できます。'), ('approvals.proposeLocked', 'vi', 'Chỉ {{owner}} được đổi tên, biểu tượng và màu của danh mục này.'), ('approvals.proposeLocked', 'en', 'Only {{owner}} can change the name, icon and colour.'),
  ('approvals.proposeDeleteTitle', 'ja', '「{{name}}」の削除を提案しますか？'), ('approvals.proposeDeleteTitle', 'vi', 'Đề xuất xoá "{{name}}"?'), ('approvals.proposeDeleteTitle', 'en', 'Propose deleting "{{name}}"?'),
  ('approvals.proposeDeleteMsg', 'ja', '{{owner}} さんが承認すると削除され、取引は未分類になります。'), ('approvals.proposeDeleteMsg', 'vi', 'Khi {{owner}} duyệt, nhóm sẽ bị xoá và các giao dịch trong đó thành chưa phân loại.'), ('approvals.proposeDeleteMsg', 'en', 'Once {{owner}} approves, it is deleted and its transactions become uncategorized.'),
  ('approvals.errNoChange', 'ja', '変更がありません'), ('approvals.errNoChange', 'vi', 'Không có gì thay đổi'), ('approvals.errNoChange', 'en', 'Nothing changed'),
  ('approvals.errTaken', 'ja', 'このキーワード／ルールはすでに使われています'), ('approvals.errTaken', 'vi', 'Từ khoá / quy tắc này đã được dùng'), ('approvals.errTaken', 'en', 'This keyword or rule is already in use'),
  ('approvals.errAlready', 'ja', '同じ提案がすでに承認待ちです'), ('approvals.errAlready', 'vi', 'Bạn đã gửi đề xuất này rồi, đang chờ duyệt'), ('approvals.errAlready', 'en', 'You already proposed this'),
  ('approvals.errRootLocked', 'ja', '共有されたカテゴリ自体の名前変更・削除はできません'), ('approvals.errRootLocked', 'vi', 'Không thể đổi tên hay xoá chính danh mục được chia sẻ'), ('approvals.errRootLocked', 'en', 'The shared category itself can''t be renamed or deleted'),
  ('approvals.errNoPermission', 'ja', 'この操作の権限がありません'), ('approvals.errNoPermission', 'vi', 'Bạn không có quyền làm việc này'), ('approvals.errNoPermission', 'en', 'You don''t have permission for this'),
  ('approvals.errGone', 'ja', '対象が見つかりません'), ('approvals.errGone', 'vi', 'Không tìm thấy mục này'), ('approvals.errGone', 'en', 'That item no longer exists'),
  ('approvals.errReviewed', 'ja', 'この提案はすでに処理されています'), ('approvals.errReviewed', 'vi', 'Đề xuất này đã được xử lý'), ('approvals.errReviewed', 'en', 'This proposal was already handled'),
  ('approvals.tabHistory', 'ja', '履歴'), ('approvals.tabHistory', 'vi', 'Lịch sử'), ('approvals.tabHistory', 'en', 'History'),
  ('approvals.histTitle', 'ja', '変更履歴'), ('approvals.histTitle', 'vi', 'Lịch sử thay đổi'), ('approvals.histTitle', 'en', 'Change history'),
  ('approvals.histSub', 'ja', 'このカテゴリとサブカテゴリの取引・予算・キーワード・提案'), ('approvals.histSub', 'vi', 'Giao dịch, ngân sách, từ khoá và đề xuất của danh mục này và các nhóm con'), ('approvals.histSub', 'en', 'Transactions, budgets, keywords and proposals in this category and its sub-categories'),
  ('approvals.histEmpty', 'ja', 'まだ変更はありません'), ('approvals.histEmpty', 'vi', 'Chưa có thay đổi nào'), ('approvals.histEmpty', 'en', 'No changes yet'),
  ('approvals.histMore', 'ja', 'さらに表示'), ('approvals.histMore', 'vi', 'Xem thêm'), ('approvals.histMore', 'en', 'Show more'),
  ('approvals.histTxCreate', 'ja', '取引を追加'), ('approvals.histTxCreate', 'vi', 'đã thêm giao dịch'), ('approvals.histTxCreate', 'en', 'added a transaction'),
  ('approvals.histTxUpdate', 'ja', '取引を編集'), ('approvals.histTxUpdate', 'vi', 'đã sửa giao dịch'), ('approvals.histTxUpdate', 'en', 'edited a transaction'),
  ('approvals.histTxDelete', 'ja', '取引を削除'), ('approvals.histTxDelete', 'vi', 'đã xoá giao dịch'), ('approvals.histTxDelete', 'en', 'deleted a transaction'),
  ('approvals.histCatCreate', 'ja', 'サブカテゴリを作成'), ('approvals.histCatCreate', 'vi', 'đã tạo nhóm'), ('approvals.histCatCreate', 'en', 'created a group'),
  ('approvals.histCatUpdate', 'ja', 'カテゴリを編集'), ('approvals.histCatUpdate', 'vi', 'đã sửa nhóm'), ('approvals.histCatUpdate', 'en', 'edited a group'),
  ('approvals.histCatDelete', 'ja', 'サブカテゴリを削除'), ('approvals.histCatDelete', 'vi', 'đã xoá nhóm'), ('approvals.histCatDelete', 'en', 'deleted a group'),
  ('approvals.histBudgetCreate', 'ja', '予算を設定'), ('approvals.histBudgetCreate', 'vi', 'đã đặt ngân sách'), ('approvals.histBudgetCreate', 'en', 'set a budget'),
  ('approvals.histBudgetUpdate', 'ja', '予算を変更'), ('approvals.histBudgetUpdate', 'vi', 'đã đổi ngân sách'), ('approvals.histBudgetUpdate', 'en', 'changed a budget'),
  ('approvals.histBudgetDelete', 'ja', '予算を削除'), ('approvals.histBudgetDelete', 'vi', 'đã bỏ ngân sách'), ('approvals.histBudgetDelete', 'en', 'removed a budget'),
  ('approvals.histRuleCreate', 'ja', 'キーワード／ルールを追加'), ('approvals.histRuleCreate', 'vi', 'đã thêm từ khoá / quy tắc'), ('approvals.histRuleCreate', 'en', 'added a keyword / rule'),
  ('approvals.histRuleUpdate', 'ja', 'ルールを変更'), ('approvals.histRuleUpdate', 'vi', 'đã đổi quy tắc'), ('approvals.histRuleUpdate', 'en', 'changed a rule'),
  ('approvals.histRuleDelete', 'ja', 'キーワード／ルールを削除'), ('approvals.histRuleDelete', 'vi', 'đã xoá từ khoá / quy tắc'), ('approvals.histRuleDelete', 'en', 'removed a keyword / rule'),
  ('approvals.histProposed', 'ja', 'が提案'), ('approvals.histProposed', 'vi', 'đề xuất'), ('approvals.histProposed', 'en', 'proposed'),
  ('approvals.histApprovedBy', 'ja', '{{name}} さんが承認'), ('approvals.histApprovedBy', 'vi', '{{name}} đã duyệt'), ('approvals.histApprovedBy', 'en', 'approved by {{name}}'),
  ('approvals.histRejectedBy', 'ja', '{{name}} さんが却下'), ('approvals.histRejectedBy', 'vi', '{{name}} đã từ chối'), ('approvals.histRejectedBy', 'en', 'declined by {{name}}'),
  ('approvals.histSystem', 'ja', 'システム'), ('approvals.histSystem', 'vi', 'Hệ thống'), ('approvals.histSystem', 'en', 'System'),
  ('approvals.fAmount', 'ja', '金額'), ('approvals.fAmount', 'vi', 'Số tiền'), ('approvals.fAmount', 'en', 'Amount'),
  ('approvals.fDate', 'ja', '日付'), ('approvals.fDate', 'vi', 'Ngày'), ('approvals.fDate', 'en', 'Date'),
  ('approvals.fCategory', 'ja', 'カテゴリ'), ('approvals.fCategory', 'vi', 'Danh mục'), ('approvals.fCategory', 'en', 'Category'),
  ('approvals.fAccount', 'ja', '口座'), ('approvals.fAccount', 'vi', 'Tài khoản'), ('approvals.fAccount', 'en', 'Account'),
  ('approvals.fNotes', 'ja', 'メモ'), ('approvals.fNotes', 'vi', 'Ghi chú'), ('approvals.fNotes', 'en', 'Notes'),
  ('approvals.fPaidBy', 'ja', '支払者'), ('approvals.fPaidBy', 'vi', 'Người trả'), ('approvals.fPaidBy', 'en', 'Paid by'),
  ('approvals.fStatus', 'ja', '状態'), ('approvals.fStatus', 'vi', 'Trạng thái'), ('approvals.fStatus', 'en', 'Status'),
  ('approvals.fType', 'ja', '種類'), ('approvals.fType', 'vi', 'Loại'), ('approvals.fType', 'en', 'Type'),
  ('approvals.fMerchant', 'ja', '店舗'), ('approvals.fMerchant', 'vi', 'Cửa hàng'), ('approvals.fMerchant', 'en', 'Merchant'),
  ('approvals.fShared', 'ja', '共有'), ('approvals.fShared', 'vi', 'Chia sẻ'), ('approvals.fShared', 'en', 'Shared'),
  ('approvals.fOwner', 'ja', '所有者'), ('approvals.fOwner', 'vi', 'Chủ sở hữu'), ('approvals.fOwner', 'en', 'Owner'),
  ('approvals.navBadge', 'ja', '{{count}} 件の承認待ち'), ('approvals.navBadge', 'vi', '{{count}} đề xuất chờ duyệt'), ('approvals.navBadge', 'en', '{{count}} to review'),
  ('approvals.pushTitle', 'ja', 'この端末のプッシュ通知'), ('approvals.pushTitle', 'vi', 'Thông báo đẩy trên thiết bị này'), ('approvals.pushTitle', 'en', 'Push on this device'),
  ('approvals.pushOff', 'ja', '承認が必要な提案が届いたらすぐに通知します。'), ('approvals.pushOff', 'vi', 'Bật để nhận thông báo ngay khi có đề xuất cần bạn duyệt.'), ('approvals.pushOff', 'en', 'Get notified as soon as something needs your approval.'),
  ('approvals.pushOn', 'ja', 'この端末で受信中'), ('approvals.pushOn', 'vi', 'Đang bật trên thiết bị này'), ('approvals.pushOn', 'en', 'On for this device'),
  ('approvals.pushEnable', 'ja', 'プッシュ通知をオン'), ('approvals.pushEnable', 'vi', 'Bật thông báo đẩy'), ('approvals.pushEnable', 'en', 'Turn on push'),
  ('approvals.pushDisable', 'ja', 'オフにする'), ('approvals.pushDisable', 'vi', 'Tắt'), ('approvals.pushDisable', 'en', 'Turn off'),
  ('approvals.pushEnabled', 'ja', 'プッシュ通知をオンにしました'), ('approvals.pushEnabled', 'vi', 'Đã bật thông báo đẩy'), ('approvals.pushEnabled', 'en', 'Push notifications on'),
  ('approvals.pushDisabled', 'ja', 'プッシュ通知をオフにしました'), ('approvals.pushDisabled', 'vi', 'Đã tắt thông báo đẩy trên thiết bị này'), ('approvals.pushDisabled', 'en', 'Push turned off for this device'),
  ('approvals.pushDenied', 'ja', 'ブラウザで通知がブロックされています。ブラウザの設定で許可してください。'), ('approvals.pushDenied', 'vi', 'Trình duyệt đang chặn thông báo. Hãy cho phép trong cài đặt của trình duyệt.'), ('approvals.pushDenied', 'en', 'Notifications are blocked. Allow them in your browser settings.'),
  ('approvals.pushUnsupported', 'ja', 'この端末はプッシュ通知に対応していません（iPhone はホーム画面に追加してから）。'), ('approvals.pushUnsupported', 'vi', 'Thiết bị này chưa hỗ trợ thông báo đẩy (iPhone: thêm app vào Màn hình chính trước).'), ('approvals.pushUnsupported', 'en', 'This device can''t receive push (on iPhone, add the app to the Home Screen first).'),
  ('approvals.pushNotConfigured', 'ja', 'サーバーでプッシュ通知が設定されていません。'), ('approvals.pushNotConfigured', 'vi', 'Máy chủ chưa cấu hình thông báo đẩy.'), ('approvals.pushNotConfigured', 'en', 'Push isn''t configured on the server.'),
  ('approvals.live', 'ja', '{{name}} さんから新しい提案'), ('approvals.live', 'vi', 'Đề xuất mới từ {{name}}'), ('approvals.live', 'en', 'New proposal from {{name}}')
on conflict (key, language_code) do update set value = excluded.value, updated_at = now();
