-- Ledger management page texts
-- (fresh databases get these from the 0016 seed).
insert into public.translation_keys (key, namespace, is_user_editable) values
  ('lm.title', 'lm', false),
  ('lm.short', 'lm', false),
  ('lm.subtitle', 'lm', false),
  ('lm.heroSub', 'lm', false),
  ('lm.plusInvites', 'lm', false),
  ('lm.statMembers', 'lm', false),
  ('lm.statMembersSub', 'lm', false),
  ('lm.statShared', 'lm', false),
  ('lm.statSharedSub', 'lm', false),
  ('lm.statPending', 'lm', false),
  ('lm.statPendingSub', 'lm', false),
  ('lm.statWeek', 'lm', false),
  ('lm.statWeekSub', 'lm', false),
  ('lm.membersTitle', 'lm', false),
  ('lm.membersSub', 'lm', false),
  ('lm.invite', 'lm', false),
  ('lm.inviteMember', 'lm', false),
  ('lm.colMember', 'lm', false),
  ('lm.colRole', 'lm', false),
  ('lm.colCategories', 'lm', false),
  ('lm.colTx', 'lm', false),
  ('lm.colActive', 'lm', false),
  ('lm.you', 'lm', false),
  ('lm.nCategories', 'lm', false),
  ('lm.never', 'lm', false),
  ('lm.inviteRow', 'lm', false),
  ('lm.copyLink', 'lm', false),
  ('lm.attentionTitle', 'lm', false),
  ('lm.attPending', 'lm', false),
  ('lm.attPendingSub', 'lm', false),
  ('lm.review', 'lm', false),
  ('lm.attInvite', 'lm', false),
  ('lm.attInviteSub', 'lm', false),
  ('lm.attPrivate', 'lm', false),
  ('lm.share', 'lm', false),
  ('lm.attWaiting', 'lm', false),
  ('lm.attWaitingSub', 'lm', false),
  ('lm.allGood', 'lm', false),
  ('lm.sharedTitle', 'lm', false),
  ('lm.sharedSub', 'lm', false),
  ('lm.bulkShare', 'lm', false),
  ('lm.ownedBy', 'lm', false),
  ('lm.private', 'lm', false),
  ('lm.rolesTitle', 'lm', false),
  ('lm.customFor', 'lm', false),
  ('lm.settingsTitle', 'lm', false),
  ('lm.edit', 'lm', false),
  ('lm.setName', 'lm', false),
  ('lm.setType', 'lm', false),
  ('lm.setTimezone', 'lm', false),
  ('lm.setFiscal', 'lm', false),
  ('lm.setApproval', 'lm', false),
  ('lm.setApprovalValue', 'lm', false),
  ('lm.setInvite', 'lm', false),
  ('lm.setInviteValue', 'lm', false),
  ('lm.activityTitle', 'lm', false),
  ('lm.auditLog', 'lm', false),
  ('lm.noActivity', 'lm', false),
  ('lm.act_create', 'lm', false),
  ('lm.act_update', 'lm', false),
  ('lm.act_delete', 'lm', false),
  ('lm.ent_transaction', 'lm', false),
  ('lm.ent_category', 'lm', false),
  ('lm.ent_account', 'lm', false),
  ('lm.ent_budget', 'lm', false),
  ('lm.ent_category_rule', 'lm', false),
  ('lm.ent_member', 'lm', false),
  ('lm.ent_ledger', 'lm', false),
  ('lm.ent_recurring', 'lm', false),
  ('lm.level', 'lm', false),
  ('lm.level_view', 'lm', false),
  ('lm.level_write', 'lm', false),
  ('lm.level_propose', 'lm', false),
  ('lm.level_manage', 'lm', false),
  ('lm.levelDesc_view', 'lm', false),
  ('lm.levelDesc_write', 'lm', false),
  ('lm.levelDesc_propose', 'lm', false),
  ('lm.levelDesc_manage', 'lm', false),
  ('lm.owner', 'lm', false),
  ('lm.ownCategory', 'lm', false),
  ('lm.viewBadge', 'lm', false),
  ('lm.editingBadge', 'lm', false),
  ('lm.lastActive', 'lm', false),
  ('lm.statCategories', 'lm', false),
  ('lm.statTx', 'lm', false),
  ('lm.statPendingMember', 'lm', false),
  ('lm.statJoined', 'lm', false),
  ('lm.editAccess', 'lm', false),
  ('lm.cancel', 'lm', false),
  ('lm.save', 'lm', false),
  ('lm.saveN', 'lm', false),
  ('lm.saved', 'lm', false),
  ('lm.unsaved', 'lm', false),
  ('lm.noChanges', 'lm', false),
  ('lm.discardTitle', 'lm', false),
  ('lm.discardMsg', 'lm', false),
  ('lm.discard', 'lm', false),
  ('lm.memberCatsTitle', 'lm', false),
  ('lm.memberCatsSub', 'lm', false),
  ('lm.noShared', 'lm', false),
  ('lm.notShared', 'lm', false),
  ('lm.notSharedShort', 'lm', false),
  ('lm.splitShort', 'lm', false),
  ('lm.memberActivity', 'lm', false),
  ('lm.roleIs', 'lm', false),
  ('lm.canDo', 'lm', false),
  ('lm.custom', 'lm', false),
  ('lm.readOnlyNote', 'lm', false),
  ('lm.editCatsTitle', 'lm', false),
  ('lm.editCatsSub', 'lm', false),
  ('lm.selectAll', 'lm', false),
  ('lm.clearAll', 'lm', false),
  ('lm.searchCats', 'lm', false),
  ('lm.levelHint', 'lm', false),
  ('lm.changed', 'lm', false),
  ('lm.splitHint', 'lm', false),
  ('lm.splitNote', 'lm', false),
  ('lm.noOwnCats', 'lm', false),
  ('lm.othersCatsNote', 'lm', false),
  ('lm.roleTitle', 'lm', false),
  ('lm.roleLocked', 'lm', false),
  ('lm.permsTitle', 'lm', false),
  ('lm.permsSub', 'lm', false),
  ('lm.resetDefaults', 'lm', false),
  ('lm.perm_transaction_create', 'lm', false),
  ('lm.perm_transaction_update', 'lm', false),
  ('lm.perm_transaction_delete', 'lm', false),
  ('lm.perm_category_create', 'lm', false),
  ('lm.perm_account_create', 'lm', false),
  ('lm.perm_import_create', 'lm', false),
  ('lm.perm_recurring_create', 'lm', false),
  ('lm.perm_budget_update', 'lm', false),
  ('lm.perm_report_read', 'lm', false),
  ('lm.perm_report_export', 'lm', false),
  ('lm.perm_audit_read', 'lm', false),
  ('lm.perm_member_invite', 'lm', false),
  ('lm.dangerTitle', 'lm', false),
  ('lm.transfer', 'lm', false),
  ('lm.remove', 'lm', false),
  ('lm.memberGone', 'lm', false),
  ('lm.backToLedger', 'lm', false),
  ('lm.bulkTitle', 'lm', false),
  ('lm.bulkSub', 'lm', false),
  ('lm.bulkStep1', 'lm', false),
  ('lm.bulkStep2', 'lm', false),
  ('lm.bulkStep3', 'lm', false),
  ('lm.bulkNoPeople', 'lm', false),
  ('lm.unshare', 'lm', false),
  ('lm.unshareDesc', 'lm', false),
  ('lm.bulkPick', 'lm', false),
  ('lm.bulkSummary', 'lm', false),
  ('lm.apply', 'lm', false),
  ('lm.bulkDone', 'lm', false),
  ('lm.err_CATEGORY_NOT_OWNED', 'lm', false),
  ('lm.err_CANNOT_GRANT', 'lm', false),
  ('lm.err_NOT_ALLOWED', 'lm', false),
  ('lm.err_CANNOT_EDIT_SELF', 'lm', false),
  ('lm.err_MEMBER_NOT_FOUND', 'lm', false),
  ('approvals.applied', 'approvals', false),
  ('approvals.errLevel', 'approvals', false),
  ('txform.errorCategoryReadOnly', 'txform', false)
on conflict (key) do nothing;

insert into public.translations (key, language_code, value) values
  ('lm.title', 'ja', '台帳の管理'), ('lm.title', 'vi', 'Quản lý sổ'), ('lm.title', 'en', 'Ledger management'),
  ('lm.short', 'ja', '台帳'), ('lm.short', 'vi', 'Sổ'), ('lm.short', 'en', 'Ledger'),
  ('lm.subtitle', 'ja', 'メンバー・共有・設定のまとめ。表示のみで、変えたいときに「編集」を押します。'), ('lm.subtitle', 'vi', 'Tổng hợp thành viên, chia sẻ và cài đặt — mặc định chỉ xem, bấm Sửa khi muốn thay đổi.'), ('lm.subtitle', 'en', 'Members, sharing and settings at a glance — read-only until you choose to edit.'),
  ('lm.heroSub', 'ja', 'オーナー {{owner}} · 作成 {{date}} · {{currency}}'), ('lm.heroSub', 'vi', 'Chủ sổ {{owner}} · tạo {{date}} · {{currency}}'), ('lm.heroSub', 'en', 'Owner {{owner}} · created {{date}} · {{currency}}'),
  ('lm.plusInvites', 'ja', '+{{count}} 件の招待'), ('lm.plusInvites', 'vi', '+{{count}} lời mời'), ('lm.plusInvites', 'en', '+{{count}} invites'),
  ('lm.statMembers', 'ja', 'メンバー'), ('lm.statMembers', 'vi', 'Thành viên'), ('lm.statMembers', 'en', 'Members'),
  ('lm.statMembersSub', 'ja', '招待中 {{count}} 件'), ('lm.statMembersSub', 'vi', '{{count}} lời mời đang chờ'), ('lm.statMembersSub', 'en', '{{count}} pending invites'),
  ('lm.statShared', 'ja', '共有カテゴリ'), ('lm.statShared', 'vi', 'Danh mục chia sẻ'), ('lm.statShared', 'en', 'Shared categories'),
  ('lm.statSharedSub', 'ja', '自分だけ {{count}} 件'), ('lm.statSharedSub', 'vi', '{{count}} của bạn còn riêng tư'), ('lm.statSharedSub', 'en', '{{count}} of yours still private'),
  ('lm.statPending', 'ja', '承認待ち'), ('lm.statPending', 'vi', 'Chờ duyệt'), ('lm.statPending', 'en', 'To approve'),
  ('lm.statPendingSub', 'ja', 'あなた宛ての提案'), ('lm.statPendingSub', 'vi', 'đề xuất gửi bạn'), ('lm.statPendingSub', 'en', 'proposals for you'),
  ('lm.statWeek', 'ja', '過去7日'), ('lm.statWeek', 'vi', '7 ngày qua'), ('lm.statWeek', 'en', 'Last 7 days'),
  ('lm.statWeekSub', 'ja', '台帳での変更'), ('lm.statWeekSub', 'vi', 'thay đổi trong sổ'), ('lm.statWeekSub', 'en', 'changes in the ledger'),
  ('lm.membersTitle', 'ja', 'メンバー · {{count}}'), ('lm.membersTitle', 'vi', 'Thành viên · {{count}}'), ('lm.membersTitle', 'en', 'Members · {{count}}'),
  ('lm.membersSub', 'ja', '名前を押すと権限の詳細が開きます'), ('lm.membersSub', 'vi', 'Bấm vào một người để xem chi tiết quyền'), ('lm.membersSub', 'en', 'Open someone to see their access in detail'),
  ('lm.invite', 'ja', '招待'), ('lm.invite', 'vi', 'Mời'), ('lm.invite', 'en', 'Invite'),
  ('lm.inviteMember', 'ja', 'メンバーを招待'), ('lm.inviteMember', 'vi', 'Mời thành viên'), ('lm.inviteMember', 'en', 'Invite member'),
  ('lm.colMember', 'ja', 'メンバー'), ('lm.colMember', 'vi', 'Thành viên'), ('lm.colMember', 'en', 'Member'),
  ('lm.colRole', 'ja', '役割'), ('lm.colRole', 'vi', 'Vai trò'), ('lm.colRole', 'en', 'Role'),
  ('lm.colCategories', 'ja', '使えるカテゴリ'), ('lm.colCategories', 'vi', 'Danh mục dùng được'), ('lm.colCategories', 'en', 'Categories'),
  ('lm.colTx', 'ja', '取引'), ('lm.colTx', 'vi', 'Giao dịch'), ('lm.colTx', 'en', 'Transactions'),
  ('lm.colActive', 'ja', '最終操作'), ('lm.colActive', 'vi', 'Hoạt động'), ('lm.colActive', 'en', 'Last active'),
  ('lm.you', 'ja', '（あなた）'), ('lm.you', 'vi', '(bạn)'), ('lm.you', 'en', '(you)'),
  ('lm.nCategories', 'ja', '{{count}} カテゴリ'), ('lm.nCategories', 'vi', '{{count}} danh mục'), ('lm.nCategories', 'en', '{{count}} categories'),
  ('lm.never', 'ja', '記録なし'), ('lm.never', 'vi', 'Chưa có'), ('lm.never', 'en', 'No activity yet'),
  ('lm.inviteRow', 'ja', '招待 · {{role}} · 期限 {{when}}'), ('lm.inviteRow', 'vi', 'Lời mời · {{role}} · hết hạn {{when}}'), ('lm.inviteRow', 'en', 'Invite · {{role}} · expires {{when}}'),
  ('lm.copyLink', 'ja', 'リンクをコピー'), ('lm.copyLink', 'vi', 'Sao chép liên kết'), ('lm.copyLink', 'en', 'Copy link'),
  ('lm.attentionTitle', 'ja', '確認が必要'), ('lm.attentionTitle', 'vi', 'Cần chú ý'), ('lm.attentionTitle', 'en', 'Needs attention'),
  ('lm.attPending', 'ja', '承認待ちの提案 {{count}} 件'), ('lm.attPending', 'vi', '{{count}} đề xuất chờ bạn duyệt'), ('lm.attPending', 'en', '{{count}} proposals waiting for you'),
  ('lm.attPendingSub', 'ja', '予算・サブカテゴリ・キーワード・ルール'), ('lm.attPendingSub', 'vi', 'Ngân sách, nhóm con, từ khoá, quy tắc'), ('lm.attPendingSub', 'en', 'Budgets, subcategories, keywords, rules'),
  ('lm.review', 'ja', '確認'), ('lm.review', 'vi', 'Duyệt'), ('lm.review', 'en', 'Review'),
  ('lm.attInvite', 'ja', '{{email}} への招待'), ('lm.attInvite', 'vi', 'Lời mời {{email}}'), ('lm.attInvite', 'en', 'Invite to {{email}}'),
  ('lm.attInviteSub', 'ja', '未承諾 · 期限 {{when}}'), ('lm.attInviteSub', 'vi', 'Chưa nhận · hết hạn {{when}}'), ('lm.attInviteSub', 'en', 'Not accepted · expires {{when}}'),
  ('lm.attPrivate', 'ja', '誰とも共有していないカテゴリ {{count}} 件'), ('lm.attPrivate', 'vi', '{{count}} danh mục chưa chia sẻ với ai'), ('lm.attPrivate', 'en', '{{count}} categories shared with nobody'),
  ('lm.share', 'ja', '共有'), ('lm.share', 'vi', 'Chia sẻ'), ('lm.share', 'en', 'Share'),
  ('lm.attWaiting', 'ja', '{{name}} さんの提案 {{count}} 件が承認待ち'), ('lm.attWaiting', 'vi', '{{name}} có {{count}} đề xuất đang chờ duyệt'), ('lm.attWaiting', 'en', '{{name}} has {{count}} proposals waiting'),
  ('lm.attWaitingSub', 'ja', 'カテゴリのオーナーが確認します'), ('lm.attWaitingSub', 'vi', 'Chủ danh mục sẽ duyệt'), ('lm.attWaitingSub', 'en', 'The category owner reviews them'),
  ('lm.allGood', 'ja', '特にありません'), ('lm.allGood', 'vi', 'Mọi thứ đều ổn'), ('lm.allGood', 'en', 'Nothing needs you right now'),
  ('lm.sharedTitle', 'ja', '共有カテゴリ · {{shared}}/{{total}}'), ('lm.sharedTitle', 'vi', 'Danh mục chia sẻ · {{shared}}/{{total}}'), ('lm.sharedTitle', 'en', 'Shared categories · {{shared}}/{{total}}'),
  ('lm.sharedSub', 'ja', 'アイコンの枠の色 = その人の権限'), ('lm.sharedSub', 'vi', 'Viền màu quanh ảnh = mức quyền của người đó'), ('lm.sharedSub', 'en', 'Ring colour = that person''s access level'),
  ('lm.bulkShare', 'ja', 'まとめて共有'), ('lm.bulkShare', 'vi', 'Chia sẻ hàng loạt'), ('lm.bulkShare', 'en', 'Share in bulk'),
  ('lm.ownedBy', 'ja', '{{name}} さんのもの'), ('lm.ownedBy', 'vi', 'của {{name}}'), ('lm.ownedBy', 'en', '{{name}}''s'),
  ('lm.private', 'ja', '非公開'), ('lm.private', 'vi', 'Riêng tư'), ('lm.private', 'en', 'Private'),
  ('lm.rolesTitle', 'ja', '役割と権限'), ('lm.rolesTitle', 'vi', 'Vai trò & quyền'), ('lm.rolesTitle', 'en', 'Roles & permissions'),
  ('lm.customFor', 'ja', '{{name}}：個別設定 {{count}}'), ('lm.customFor', 'vi', '{{name}}: {{count}} quyền tuỳ chỉnh'), ('lm.customFor', 'en', '{{name}}: {{count}} custom'),
  ('lm.settingsTitle', 'ja', '台帳の設定'), ('lm.settingsTitle', 'vi', 'Cài đặt sổ'), ('lm.settingsTitle', 'en', 'Ledger settings'),
  ('lm.edit', 'ja', '編集'), ('lm.edit', 'vi', 'Sửa'), ('lm.edit', 'en', 'Edit'),
  ('lm.setName', 'ja', '名前 · 通貨'), ('lm.setName', 'vi', 'Tên sổ · tiền tệ'), ('lm.setName', 'en', 'Name · currency'),
  ('lm.setType', 'ja', '種類'), ('lm.setType', 'vi', 'Loại sổ'), ('lm.setType', 'en', 'Type'),
  ('lm.setTimezone', 'ja', 'タイムゾーン'), ('lm.setTimezone', 'vi', 'Múi giờ'), ('lm.setTimezone', 'en', 'Time zone'),
  ('lm.setFiscal', 'ja', '年度の開始'), ('lm.setFiscal', 'vi', 'Năm tài chính bắt đầu'), ('lm.setFiscal', 'en', 'Fiscal year starts'),
  ('lm.setApproval', 'ja', '変更の承認'), ('lm.setApproval', 'vi', 'Duyệt thay đổi'), ('lm.setApproval', 'en', 'Approvals'),
  ('lm.setApprovalValue', 'ja', '「提案」はオーナーの承認が必要、「共同管理」は即時反映'), ('lm.setApprovalValue', 'vi', 'Mức Đề xuất cần chủ danh mục duyệt; Đồng quản lý áp dụng ngay'), ('lm.setApprovalValue', 'en', '“Propose” needs the owner; “Co-manage” applies at once'),
  ('lm.setInvite', 'ja', '招待リンク'), ('lm.setInvite', 'vi', 'Liên kết mời'), ('lm.setInvite', 'en', 'Invite links'),
  ('lm.setInviteValue', 'ja', '7日で期限切れ · 1回のみ使用可'), ('lm.setInviteValue', 'vi', 'Hết hạn sau 7 ngày · dùng một lần'), ('lm.setInviteValue', 'en', 'Expire after 7 days · single use'),
  ('lm.activityTitle', 'ja', '最近の動き'), ('lm.activityTitle', 'vi', 'Hoạt động gần đây'), ('lm.activityTitle', 'en', 'Recent activity'),
  ('lm.auditLog', 'ja', '操作ログ'), ('lm.auditLog', 'vi', 'Nhật ký'), ('lm.auditLog', 'en', 'Audit log'),
  ('lm.noActivity', 'ja', 'まだ記録がありません'), ('lm.noActivity', 'vi', 'Chưa có hoạt động nào'), ('lm.noActivity', 'en', 'No activity yet'),
  ('lm.act_create', 'ja', '追加しました'), ('lm.act_create', 'vi', 'đã thêm'), ('lm.act_create', 'en', 'added'),
  ('lm.act_update', 'ja', '変更しました'), ('lm.act_update', 'vi', 'đã sửa'), ('lm.act_update', 'en', 'changed'),
  ('lm.act_delete', 'ja', '削除しました'), ('lm.act_delete', 'vi', 'đã xoá'), ('lm.act_delete', 'en', 'deleted'),
  ('lm.ent_transaction', 'ja', '取引'), ('lm.ent_transaction', 'vi', 'giao dịch'), ('lm.ent_transaction', 'en', 'a transaction'),
  ('lm.ent_category', 'ja', 'カテゴリ'), ('lm.ent_category', 'vi', 'danh mục'), ('lm.ent_category', 'en', 'a category'),
  ('lm.ent_account', 'ja', '口座'), ('lm.ent_account', 'vi', 'tài khoản'), ('lm.ent_account', 'en', 'an account'),
  ('lm.ent_budget', 'ja', '予算'), ('lm.ent_budget', 'vi', 'ngân sách'), ('lm.ent_budget', 'en', 'a budget'),
  ('lm.ent_category_rule', 'ja', 'ルール'), ('lm.ent_category_rule', 'vi', 'quy tắc'), ('lm.ent_category_rule', 'en', 'a rule'),
  ('lm.ent_member', 'ja', 'メンバー'), ('lm.ent_member', 'vi', 'thành viên'), ('lm.ent_member', 'en', 'a member'),
  ('lm.ent_ledger', 'ja', '台帳'), ('lm.ent_ledger', 'vi', 'sổ'), ('lm.ent_ledger', 'en', 'the ledger'),
  ('lm.ent_recurring', 'ja', '定期取引'), ('lm.ent_recurring', 'vi', 'giao dịch định kỳ'), ('lm.ent_recurring', 'en', 'a recurring item'),
  ('lm.level', 'ja', '権限'), ('lm.level', 'vi', 'Mức quyền'), ('lm.level', 'en', 'Access level'),
  ('lm.level_view', 'ja', '閲覧'), ('lm.level_view', 'vi', 'Xem'), ('lm.level_view', 'en', 'View'),
  ('lm.level_write', 'ja', '記録'), ('lm.level_write', 'vi', 'Ghi'), ('lm.level_write', 'en', 'Write'),
  ('lm.level_propose', 'ja', '提案'), ('lm.level_propose', 'vi', 'Đề xuất'), ('lm.level_propose', 'en', 'Propose'),
  ('lm.level_manage', 'ja', '共同管理'), ('lm.level_manage', 'vi', 'Đồng quản lý'), ('lm.level_manage', 'en', 'Co-manage'),
  ('lm.levelDesc_view', 'ja', '取引と数字を見るだけ'), ('lm.levelDesc_view', 'vi', 'Xem giao dịch & số liệu'), ('lm.levelDesc_view', 'en', 'Sees transactions and figures'),
  ('lm.levelDesc_write', 'ja', '閲覧＋自分の取引を記録'), ('lm.levelDesc_write', 'vi', 'Xem + ghi giao dịch của mình'), ('lm.levelDesc_write', 'en', 'View + record their own transactions'),
  ('lm.levelDesc_propose', 'ja', '記録＋予算・サブカテゴリ・キーワードを提案'), ('lm.levelDesc_propose', 'vi', 'Ghi + đề xuất ngân sách, nhóm con, từ khoá'), ('lm.levelDesc_propose', 'en', 'Write + propose budgets, subcategories, keywords'),
  ('lm.levelDesc_manage', 'ja', '承認なしで直接変更'), ('lm.levelDesc_manage', 'vi', 'Sửa trực tiếp, không cần duyệt'), ('lm.levelDesc_manage', 'en', 'Changes things directly, no approval'),
  ('lm.owner', 'ja', 'オーナー'), ('lm.owner', 'vi', 'Chủ'), ('lm.owner', 'en', 'Owner'),
  ('lm.ownCategory', 'ja', '本人のカテゴリ'), ('lm.ownCategory', 'vi', 'Danh mục của chính họ'), ('lm.ownCategory', 'en', 'Their own category'),
  ('lm.viewBadge', 'ja', '表示モード'), ('lm.viewBadge', 'vi', 'Chế độ xem'), ('lm.viewBadge', 'en', 'Viewing'),
  ('lm.editingBadge', 'ja', '編集中'), ('lm.editingBadge', 'vi', 'Đang chỉnh sửa'), ('lm.editingBadge', 'en', 'Editing'),
  ('lm.lastActive', 'ja', '最終操作 {{when}}'), ('lm.lastActive', 'vi', 'hoạt động {{when}}'), ('lm.lastActive', 'en', 'active {{when}}'),
  ('lm.statCategories', 'ja', '使えるカテゴリ'), ('lm.statCategories', 'vi', 'danh mục dùng được'), ('lm.statCategories', 'en', 'categories'),
  ('lm.statTx', 'ja', '記録した取引'), ('lm.statTx', 'vi', 'giao dịch đã ghi'), ('lm.statTx', 'en', 'transactions recorded'),
  ('lm.statPendingMember', 'ja', '承認待ちの提案'), ('lm.statPendingMember', 'vi', 'đề xuất chờ duyệt'), ('lm.statPendingMember', 'en', 'proposals pending'),
  ('lm.statJoined', 'ja', '参加'), ('lm.statJoined', 'vi', 'tham gia'), ('lm.statJoined', 'en', 'joined'),
  ('lm.editAccess', 'ja', '編集'), ('lm.editAccess', 'vi', 'Chỉnh sửa'), ('lm.editAccess', 'en', 'Edit'),
  ('lm.cancel', 'ja', 'キャンセル'), ('lm.cancel', 'vi', 'Huỷ'), ('lm.cancel', 'en', 'Cancel'),
  ('lm.save', 'ja', '保存'), ('lm.save', 'vi', 'Lưu'), ('lm.save', 'en', 'Save'),
  ('lm.saveN', 'ja', '{{count}} 件の変更を保存'), ('lm.saveN', 'vi', 'Lưu {{count}} thay đổi'), ('lm.saveN', 'en', 'Save {{count}} changes'),
  ('lm.saved', 'ja', '{{name}} さんの権限を保存しました'), ('lm.saved', 'vi', 'Đã lưu quyền của {{name}}'), ('lm.saved', 'en', 'Saved {{name}}''s access'),
  ('lm.unsaved', 'ja', '未保存の変更 {{count}} 件'), ('lm.unsaved', 'vi', '{{count}} thay đổi chưa lưu'), ('lm.unsaved', 'en', '{{count}} unsaved changes'),
  ('lm.noChanges', 'ja', '変更はまだありません'), ('lm.noChanges', 'vi', 'Chưa có thay đổi'), ('lm.noChanges', 'en', 'No changes yet'),
  ('lm.discardTitle', 'ja', '変更を破棄しますか？'), ('lm.discardTitle', 'vi', 'Bỏ các thay đổi?'), ('lm.discardTitle', 'en', 'Discard changes?'),
  ('lm.discardMsg', 'ja', '保存していない変更は失われます。'), ('lm.discardMsg', 'vi', 'Những thay đổi chưa lưu sẽ mất.'), ('lm.discardMsg', 'en', 'Unsaved changes will be lost.'),
  ('lm.discard', 'ja', '破棄'), ('lm.discard', 'vi', 'Bỏ thay đổi'), ('lm.discard', 'en', 'Discard'),
  ('lm.memberCatsTitle', 'ja', '使えるカテゴリ · {{count}}'), ('lm.memberCatsTitle', 'vi', 'Danh mục được chia sẻ · {{count}}'), ('lm.memberCatsTitle', 'en', 'Categories they can use · {{count}}'),
  ('lm.memberCatsSub', 'ja', '権限と負担割合'), ('lm.memberCatsSub', 'vi', 'Mức quyền và phần chia tiền'), ('lm.memberCatsSub', 'en', 'Access level and share of the costs'),
  ('lm.noShared', 'ja', '共有されているカテゴリはありません'), ('lm.noShared', 'vi', 'Chưa được chia sẻ danh mục nào'), ('lm.noShared', 'en', 'Nothing is shared with them yet'),
  ('lm.notShared', 'ja', 'あなたのカテゴリのうち {{count}} 件は共有していません'), ('lm.notShared', 'vi', '{{count}} danh mục của bạn chưa chia sẻ với họ'), ('lm.notShared', 'en', '{{count}} of your categories are not shared with them'),
  ('lm.notSharedShort', 'ja', '共有しない'), ('lm.notSharedShort', 'vi', 'Không chia sẻ'), ('lm.notSharedShort', 'en', 'Not shared'),
  ('lm.splitShort', 'ja', '負担'), ('lm.splitShort', 'vi', 'Chia'), ('lm.splitShort', 'en', 'Share'),
  ('lm.memberActivity', 'ja', '{{name}} さんの動き'), ('lm.memberActivity', 'vi', 'Hoạt động của {{name}}'), ('lm.memberActivity', 'en', '{{name}}''s activity'),
  ('lm.roleIs', 'ja', '役割：{{role}}'), ('lm.roleIs', 'vi', 'Vai trò: {{role}}'), ('lm.roleIs', 'en', 'Role: {{role}}'),
  ('lm.canDo', 'ja', '{{name}} さんができること'), ('lm.canDo', 'vi', '{{name}} có thể'), ('lm.canDo', 'en', '{{name}} can'),
  ('lm.custom', 'ja', '個別'), ('lm.custom', 'vi', 'Tuỳ chỉnh'), ('lm.custom', 'en', 'Custom'),
  ('lm.readOnlyNote', 'ja', '役割は管理者が、カテゴリの共有は各カテゴリのオーナーが変更できます。'), ('lm.readOnlyNote', 'vi', 'Vai trò do quản trị sổ đổi; chia sẻ danh mục do chủ của từng danh mục đổi.'), ('lm.readOnlyNote', 'en', 'Roles are changed by ledger admins; sharing by each category''s owner.'),
  ('lm.editCatsTitle', 'ja', '共有するカテゴリ'), ('lm.editCatsTitle', 'vi', 'Danh mục được chia sẻ'), ('lm.editCatsTitle', 'en', 'Shared categories'),
  ('lm.editCatsSub', 'ja', 'チェックして共有し、{{name}} さんの権限と負担割合を選びます'), ('lm.editCatsSub', 'vi', 'Tick để chia sẻ, chọn mức quyền và phần chia tiền của {{name}}'), ('lm.editCatsSub', 'en', 'Tick to share, then pick {{name}}''s level and share'),
  ('lm.selectAll', 'ja', 'すべて選択'), ('lm.selectAll', 'vi', 'Chọn tất cả'), ('lm.selectAll', 'en', 'Select all'),
  ('lm.clearAll', 'ja', 'すべて解除'), ('lm.clearAll', 'vi', 'Bỏ chọn tất cả'), ('lm.clearAll', 'en', 'Clear all'),
  ('lm.searchCats', 'ja', 'カテゴリを検索…'), ('lm.searchCats', 'vi', 'Tìm danh mục…'), ('lm.searchCats', 'en', 'Search categories…'),
  ('lm.levelHint', 'ja', 'ボタンにカーソルで説明'), ('lm.levelHint', 'vi', 'Rê chuột lên mức để xem mô tả'), ('lm.levelHint', 'en', 'Hover a level for its meaning'),
  ('lm.changed', 'ja', '変更'), ('lm.changed', 'vi', 'Đã đổi'), ('lm.changed', 'en', 'Changed'),
  ('lm.splitHint', 'ja', '共有支出のうちこの人が負担する割合'), ('lm.splitHint', 'vi', 'Phần trăm chi tiêu chung người này chịu'), ('lm.splitHint', 'en', 'Share of the shared spending this person carries'),
  ('lm.splitNote', 'ja', '負担割合は「立替精算」で使われます。他の人の割合は自動で調整されます。'), ('lm.splitNote', 'vi', 'Phần chia tiền dùng cho phần Thanh toán lại; phần của những người còn lại tự điều chỉnh theo.'), ('lm.splitNote', 'en', 'The split is used for settling up; everyone else''s share adjusts to fit.'),
  ('lm.noOwnCats', 'ja', '共有できるのは自分のカテゴリだけです。まだありません。'), ('lm.noOwnCats', 'vi', 'Bạn chỉ chia sẻ được danh mục của mình — hiện chưa có.'), ('lm.noOwnCats', 'en', 'You can only share your own categories — you have none yet.'),
  ('lm.othersCatsNote', 'ja', '他の人のカテゴリは、そのオーナーだけが共有を変更できます。'), ('lm.othersCatsNote', 'vi', 'Danh mục của người khác chỉ chủ của nó mới đổi được việc chia sẻ.'), ('lm.othersCatsNote', 'en', 'Only a category''s owner can change who it is shared with.'),
  ('lm.roleTitle', 'ja', '役割'), ('lm.roleTitle', 'vi', 'Vai trò'), ('lm.roleTitle', 'en', 'Role'),
  ('lm.roleLocked', 'ja', 'この人の役割はあなたには変更できません。'), ('lm.roleLocked', 'vi', 'Bạn không đổi được vai trò của người này.'), ('lm.roleLocked', 'en', 'You can''t change this person''s role.'),
  ('lm.permsTitle', 'ja', '権限の詳細'), ('lm.permsTitle', 'vi', 'Quyền chi tiết'), ('lm.permsTitle', 'en', 'Permissions'),
  ('lm.permsSub', 'ja', '役割の初期値から個別に変更できます'), ('lm.permsSub', 'vi', 'Theo vai trò; có thể chỉnh riêng từng quyền'), ('lm.permsSub', 'en', 'From the role, adjustable one by one'),
  ('lm.resetDefaults', 'ja', '初期値に戻す'), ('lm.resetDefaults', 'vi', 'Về mặc định'), ('lm.resetDefaults', 'en', 'Reset'),
  ('lm.perm_transaction_create', 'ja', '取引を追加'), ('lm.perm_transaction_create', 'vi', 'Thêm giao dịch'), ('lm.perm_transaction_create', 'en', 'Add transactions'),
  ('lm.perm_transaction_update', 'ja', '自分の取引を編集'), ('lm.perm_transaction_update', 'vi', 'Sửa giao dịch của mình'), ('lm.perm_transaction_update', 'en', 'Edit their transactions'),
  ('lm.perm_transaction_delete', 'ja', '自分の取引を削除'), ('lm.perm_transaction_delete', 'vi', 'Xoá giao dịch của mình'), ('lm.perm_transaction_delete', 'en', 'Delete their transactions'),
  ('lm.perm_category_create', 'ja', '自分のカテゴリを作成'), ('lm.perm_category_create', 'vi', 'Tạo danh mục riêng'), ('lm.perm_category_create', 'en', 'Create own categories'),
  ('lm.perm_account_create', 'ja', '口座を追加'), ('lm.perm_account_create', 'vi', 'Thêm tài khoản'), ('lm.perm_account_create', 'en', 'Add accounts'),
  ('lm.perm_import_create', 'ja', 'ファイル取込・レシート読取'), ('lm.perm_import_create', 'vi', 'Nhập file & quét hoá đơn'), ('lm.perm_import_create', 'en', 'Import files & scan receipts'),
  ('lm.perm_recurring_create', 'ja', '定期取引を作成'), ('lm.perm_recurring_create', 'vi', 'Tạo giao dịch định kỳ'), ('lm.perm_recurring_create', 'en', 'Create recurring items'),
  ('lm.perm_budget_update', 'ja', '予算を設定'), ('lm.perm_budget_update', 'vi', 'Đặt ngân sách'), ('lm.perm_budget_update', 'en', 'Set budgets'),
  ('lm.perm_report_read', 'ja', 'レポートを見る'), ('lm.perm_report_read', 'vi', 'Xem báo cáo'), ('lm.perm_report_read', 'en', 'See reports'),
  ('lm.perm_report_export', 'ja', 'データを書き出す'), ('lm.perm_report_export', 'vi', 'Xuất dữ liệu'), ('lm.perm_report_export', 'en', 'Export data'),
  ('lm.perm_audit_read', 'ja', '操作ログを見る'), ('lm.perm_audit_read', 'vi', 'Xem nhật ký thao tác'), ('lm.perm_audit_read', 'en', 'See the audit log'),
  ('lm.perm_member_invite', 'ja', 'メンバーを招待'), ('lm.perm_member_invite', 'vi', 'Mời người vào sổ'), ('lm.perm_member_invite', 'en', 'Invite people'),
  ('lm.dangerTitle', 'ja', '管理'), ('lm.dangerTitle', 'vi', 'Vùng quản lý'), ('lm.dangerTitle', 'en', 'Manage'),
  ('lm.transfer', 'ja', '{{name}} さんにオーナーを譲る'), ('lm.transfer', 'vi', 'Chuyển quyền chủ sổ cho {{name}}'), ('lm.transfer', 'en', 'Make {{name}} the owner'),
  ('lm.remove', 'ja', '{{name}} さんを台帳から外す'), ('lm.remove', 'vi', 'Gỡ {{name}} khỏi sổ'), ('lm.remove', 'en', 'Remove {{name}} from the ledger'),
  ('lm.memberGone', 'ja', 'このメンバーは見つかりません'), ('lm.memberGone', 'vi', 'Không tìm thấy thành viên này'), ('lm.memberGone', 'en', 'This member was not found'),
  ('lm.backToLedger', 'ja', '台帳の管理に戻る'), ('lm.backToLedger', 'vi', 'Về Quản lý sổ'), ('lm.backToLedger', 'en', 'Back to ledger management'),
  ('lm.bulkTitle', 'ja', 'まとめて共有'), ('lm.bulkTitle', 'vi', 'Chia sẻ hàng loạt'), ('lm.bulkTitle', 'en', 'Share in bulk'),
  ('lm.bulkSub', 'ja', '複数のカテゴリを複数の人と同じ権限で共有します'), ('lm.bulkSub', 'vi', 'Chia sẻ nhiều danh mục cho nhiều người với cùng một mức quyền'), ('lm.bulkSub', 'en', 'Share several categories with several people at one level'),
  ('lm.bulkStep1', 'ja', '1 · カテゴリ（{{count}}）'), ('lm.bulkStep1', 'vi', '1 · Danh mục ({{count}})'), ('lm.bulkStep1', 'en', '1 · Categories ({{count}})'),
  ('lm.bulkStep2', 'ja', '2 · 共有する相手'), ('lm.bulkStep2', 'vi', '2 · Chia sẻ với'), ('lm.bulkStep2', 'en', '2 · Share with'),
  ('lm.bulkStep3', 'ja', '3 · 権限'), ('lm.bulkStep3', 'vi', '3 · Mức quyền'), ('lm.bulkStep3', 'en', '3 · Access level'),
  ('lm.bulkNoPeople', 'ja', 'まだ他のメンバーがいません'), ('lm.bulkNoPeople', 'vi', 'Sổ chưa có thành viên khác'), ('lm.bulkNoPeople', 'en', 'No other members yet'),
  ('lm.unshare', 'ja', '共有をやめる'), ('lm.unshare', 'vi', 'Bỏ chia sẻ'), ('lm.unshare', 'en', 'Stop sharing'),
  ('lm.unshareDesc', 'ja', '選んだ人から外します'), ('lm.unshareDesc', 'vi', 'Gỡ những người đã chọn khỏi danh mục'), ('lm.unshareDesc', 'en', 'Removes the chosen people'),
  ('lm.bulkPick', 'ja', 'カテゴリと相手を選んでください'), ('lm.bulkPick', 'vi', 'Chọn danh mục và người'), ('lm.bulkPick', 'en', 'Pick categories and people'),
  ('lm.bulkSummary', 'ja', '{{cats}} カテゴリ × {{people}} 人'), ('lm.bulkSummary', 'vi', '{{cats}} danh mục × {{people}} người'), ('lm.bulkSummary', 'en', '{{cats}} categories × {{people}} people'),
  ('lm.apply', 'ja', '適用'), ('lm.apply', 'vi', 'Áp dụng'), ('lm.apply', 'en', 'Apply'),
  ('lm.bulkDone', 'ja', '{{cats}} カテゴリを {{people}} 人に適用しました'), ('lm.bulkDone', 'vi', 'Đã áp dụng {{cats}} danh mục cho {{people}} người'), ('lm.bulkDone', 'en', 'Applied {{cats}} categories to {{people}} people'),
  ('lm.err_CATEGORY_NOT_OWNED', 'ja', '自分のカテゴリだけ共有できます'), ('lm.err_CATEGORY_NOT_OWNED', 'vi', 'Bạn chỉ chia sẻ được danh mục của mình'), ('lm.err_CATEGORY_NOT_OWNED', 'en', 'You can only share your own categories'),
  ('lm.err_CANNOT_GRANT', 'ja', '自分にない権限は渡せません'), ('lm.err_CANNOT_GRANT', 'vi', 'Không thể cấp quyền mà chính bạn không có'), ('lm.err_CANNOT_GRANT', 'en', 'You can''t give a permission you don''t have'),
  ('lm.err_NOT_ALLOWED', 'ja', 'この人の権限は変更できません'), ('lm.err_NOT_ALLOWED', 'vi', 'Bạn không được đổi quyền của người này'), ('lm.err_NOT_ALLOWED', 'en', 'You can''t change this person''s permissions'),
  ('lm.err_CANNOT_EDIT_SELF', 'ja', '自分の権限は変更できません'), ('lm.err_CANNOT_EDIT_SELF', 'vi', 'Không tự đổi quyền của chính mình'), ('lm.err_CANNOT_EDIT_SELF', 'en', 'You can''t change your own access'),
  ('lm.err_MEMBER_NOT_FOUND', 'ja', 'メンバーが見つかりません'), ('lm.err_MEMBER_NOT_FOUND', 'vi', 'Không tìm thấy thành viên'), ('lm.err_MEMBER_NOT_FOUND', 'en', 'Member not found'),
  ('approvals.applied', 'ja', '変更しました（共同管理）· {{owner}} さんに通知しました'), ('approvals.applied', 'vi', 'Đã áp dụng (đồng quản lý) · đã báo cho {{owner}}'), ('approvals.applied', 'en', 'Applied (co-manager) · {{owner}} was told'),
  ('approvals.errLevel', 'ja', 'このカテゴリでのあなたの権限では提案できません'), ('approvals.errLevel', 'vi', 'Mức quyền của bạn ở danh mục này không cho phép đề xuất'), ('approvals.errLevel', 'en', 'Your access to this category does not include proposals'),
  ('txform.errorCategoryReadOnly', 'ja', 'このカテゴリは閲覧のみで共有されています'), ('txform.errorCategoryReadOnly', 'vi', 'Danh mục này chỉ được chia sẻ để xem'), ('txform.errorCategoryReadOnly', 'en', 'This category is shared with you to view only')
on conflict (key, language_code) do update set value = excluded.value, updated_at = now();
